// Code generated by cmd/txttocode. DO NOT EDIT.
// source: cmd/txttocode/txt/rareprefix.txt
package item

type RarePrefix struct {
	ID           int
	Name         string
	ItemTypes    []string
	ExcludeTypes []string
}

var RarePrefixDesc = map[int]RarePrefix{
	156: {ID: 156, Name: "Beast", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	157: {ID: 157, Name: "Eagle", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	158: {ID: 158, Name: "Raven", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	159: {ID: 159, Name: "Viper", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	160: {ID: 160, Name: "Ghoul", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	161: {ID: 161, Name: "Skull", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	162: {ID: 162, Name: "Blood", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	163: {ID: 163, Name: "Dread", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	164: {ID: 164, Name: "Doom", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	165: {ID: 165, Name: "Grim", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	166: {ID: 166, Name: "Bone", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	167: {ID: 167, Name: "Death", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	168: {ID: 168, Name: "Shadow", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	169: {ID: 169, Name: "Storm", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	170: {ID: 170, Name: "Rune", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	171: {ID: 171, Name: "Plague", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	172: {ID: 172, Name: "Stone", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	173: {ID: 173, Name: "Wraith", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	174: {ID: 174, Name: "Spirit", ItemTypes: []string{"armo", "rod"}, ExcludeTypes: []string{}},
	175: {ID: 175, Name: "Storm", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	176: {ID: 176, Name: "Demon", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	177: {ID: 177, Name: "Cruel", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	178: {ID: 178, Name: "Empyrion", ItemTypes: []string{"rod"}, ExcludeTypes: []string{}},
	179: {ID: 179, Name: "Bramble", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	180: {ID: 180, Name: "Pain", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	181: {ID: 181, Name: "Loath", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	182: {ID: 182, Name: "Glyph", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	183: {ID: 183, Name: "Imp", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	184: {ID: 184, Name: "Fiend", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	185: {ID: 185, Name: "Hailstone", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	186: {ID: 186, Name: "Gale", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	187: {ID: 187, Name: "Dire", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	188: {ID: 188, Name: "Soul", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	189: {ID: 189, Name: "Brimstone", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	190: {ID: 190, Name: "Corpse", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	191: {ID: 191, Name: "Carrion", ItemTypes: []string{"armo", "weap"}, ExcludeTypes: []string{}},
	192: {ID: 192, Name: "Holocaust", ItemTypes: []string{"tors", "helm", "shld", "swor", "axe"}, ExcludeTypes: []string{}},
	193: {ID: 193, Name: "Havoc", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	194: {ID: 194, Name: "Bitter", ItemTypes: []string{"armo", "weap", "misc"}, ExcludeTypes: []string{}},
	195: {ID: 195, Name: "Entropy", ItemTypes: []string{"ring", "amul"}, ExcludeTypes: []string{}},
	196: {ID: 196, Name: "Chaos", ItemTypes: []string{"ring", "amul"}, ExcludeTypes: []string{}},
	197: {ID: 197, Name: "Order", ItemTypes: []string{"ring", "amul", "scep"}, ExcludeTypes: []string{}},
	198: {ID: 198, Name: "Rule", ItemTypes: []string{"rod"}, ExcludeTypes: []string{}},
	199: {ID: 199, Name: "Warp", ItemTypes: []string{}, ExcludeTypes: []string{}},
	200: {ID: 200, Name: "Rift", ItemTypes: []string{}, ExcludeTypes: []string{}},
	201: {ID: 201, Name: "Corruption", ItemTypes: []string{"ring", "amul"}, ExcludeTypes: []string{}},
}
