// Code generated by cmd/txttocode. DO NOT EDIT.
// source: cmd/txttocode/txt/setitems.txt
package item

type SetName string
type SetItemName string

const (
	SetItemNone               SetItemName = ""
	CiverbsWard               SetItemName = "Civerb's Ward"
	CiverbsIcon               SetItemName = "Civerb's Icon"
	CiverbsCudgel             SetItemName = "Civerb's Cudgel"
	HsarusIronHeel            SetItemName = "Hsarus' Iron Heel"
	HsarusIronFist            SetItemName = "Hsarus' Iron Fist"
	HsarusIronStay            SetItemName = "Hsarus' Iron Stay"
	CleglawsTooth             SetItemName = "Cleglaw's Tooth"
	CleglawsClaw              SetItemName = "Cleglaw's Claw"
	CleglawsPincers           SetItemName = "Cleglaw's Pincers"
	IrathasCollar             SetItemName = "Iratha's Collar"
	IrathasCuff               SetItemName = "Iratha's Cuff"
	IrathasCoil               SetItemName = "Iratha's Coil"
	IrathasCord               SetItemName = "Iratha's Cord"
	IsenhartsLightbrand       SetItemName = "Isenhart's Lightbrand"
	IsenhartsParry            SetItemName = "Isenhart's Parry"
	IsenhartsCase             SetItemName = "Isenhart's Case"
	IsenhartsHorns            SetItemName = "Isenhart's Horns"
	VidalasBarb               SetItemName = "Vidala's Barb"
	VidalasFetlock            SetItemName = "Vidala's Fetlock"
	VidalasAmbush             SetItemName = "Vidala's Ambush"
	VidalasSnare              SetItemName = "Vidala's Snare"
	MilabregasOrb             SetItemName = "Milabrega's Orb"
	MilabregasRod             SetItemName = "Milabrega's Rod"
	MilabregasDiadem          SetItemName = "Milabrega's Diadem"
	MilabregasRobe            SetItemName = "Milabrega's Robe"
	CathansRule               SetItemName = "Cathan's Rule"
	CathansMesh               SetItemName = "Cathan's Mesh"
	CathansVisage             SetItemName = "Cathan's Visage"
	CathansSigil              SetItemName = "Cathan's Sigil"
	CathansSeal               SetItemName = "Cathan's Seal"
	TancredsCrowbill          SetItemName = "Tancred's Crowbill"
	TancredsSpine             SetItemName = "Tancred's Spine"
	TancredsHobnails          SetItemName = "Tancred's Hobnails"
	TancredsWeird             SetItemName = "Tancred's Weird"
	TancredsSkull             SetItemName = "Tancred's Skull"
	SigonsGage                SetItemName = "Sigon's Gage"
	SigonsVisor               SetItemName = "Sigon's Visor"
	SigonsShelter             SetItemName = "Sigon's Shelter"
	SigonsSabot               SetItemName = "Sigon's Sabot"
	SigonsWrap                SetItemName = "Sigon's Wrap"
	SigonsGuard               SetItemName = "Sigon's Guard"
	InfernalCranium           SetItemName = "Infernal Cranium"
	InfernalTorch             SetItemName = "Infernal Torch"
	InfernalSign              SetItemName = "Infernal Sign"
	BerserkersHeadgear        SetItemName = "Berserker's Headgear"
	BerserkersHauberk         SetItemName = "Berserker's Hauberk"
	BerserkersHatchet         SetItemName = "Berserker's Hatchet"
	DeathsHand                SetItemName = "Death's Hand"
	DeathsGuard               SetItemName = "Death's Guard"
	DeathsTouch               SetItemName = "Death's Touch"
	AngelicSickle             SetItemName = "Angelic Sickle"
	AngelicMantle             SetItemName = "Angelic Mantle"
	AngelicHalo               SetItemName = "Angelic Halo"
	AngelicWings              SetItemName = "Angelic Wings"
	ArcticHorn                SetItemName = "Arctic Horn"
	ArcticFurs                SetItemName = "Arctic Furs"
	ArcticBinding             SetItemName = "Arctic Binding"
	ArcticMitts               SetItemName = "Arctic Mitts"
	ArcannasSign              SetItemName = "Arcanna's Sign"
	ArcannasDeathwand         SetItemName = "Arcanna's Deathwand"
	ArcannasHead              SetItemName = "Arcanna's Head"
	ArcannasFlesh             SetItemName = "Arcanna's Flesh"
	NatalyasTotem             SetItemName = "Natalya's Totem"
	NatalyasMark              SetItemName = "Natalya's Mark"
	NatalyasShadow            SetItemName = "Natalya's Shadow"
	NatalyasSoul              SetItemName = "Natalya's Soul"
	AldursStonyGaze           SetItemName = "Aldur's Stony Gaze"
	AldursDeception           SetItemName = "Aldur's Deception"
	AldursRhythm              SetItemName = "Aldur's Rhythm"
	AldursAdvance             SetItemName = "Aldur's Advance"
	ImmortalKingsWill         SetItemName = "Immortal King's Will"
	ImmortalKingsSoulCage     SetItemName = "Immortal King's Soul Cage"
	ImmortalKingsDetail       SetItemName = "Immortal King's Detail"
	ImmortalKingsForge        SetItemName = "Immortal King's Forge"
	ImmortalKingsPillar       SetItemName = "Immortal King's Pillar"
	ImmortalKingsStoneCrusher SetItemName = "Immortal King's Stone Crusher"
	TalRashasFireSpunCloth    SetItemName = "Tal Rasha's Fire-Spun Cloth"
	TalRashasAdjudication     SetItemName = "Tal Rasha's Adjudication"
	TalRashasLidlessEye       SetItemName = "Tal Rasha's Lidless Eye"
	TalRashasGuardianship     SetItemName = "Tal Rasha's Guardianship"
	TalRashasHoradricCrest    SetItemName = "Tal Rasha's Horadric Crest"
	GriswoldsValor            SetItemName = "Griswold's Valor"
	GriswoldsHeart            SetItemName = "Griswold's Heart"
	GriswoldssRedemption      SetItemName = "Griswolds's Redemption"
	GriswoldsHonor            SetItemName = "Griswold's Honor"
	TrangOulsGuise            SetItemName = "Trang-Oul's Guise"
	TrangOulsScales           SetItemName = "Trang-Oul's Scales"
	TrangOulsWing             SetItemName = "Trang-Oul's Wing"
	TrangOulsClaws            SetItemName = "Trang-Oul's Claws"
	TrangOulsGirth            SetItemName = "Trang-Oul's Girth"
	MavinasTrueSight          SetItemName = "M'avina's True Sight"
	MavinasEmbrace            SetItemName = "M'avina's Embrace"
	MavinasIcyClutch          SetItemName = "M'avina's Icy Clutch"
	MavinasTenet              SetItemName = "M'avina's Tenet"
	MavinasCaster             SetItemName = "M'avina's Caster"
	TellingofBeads            SetItemName = "Telling of Beads"
	LayingofHands             SetItemName = "Laying of Hands"
	RiteofPassage             SetItemName = "Rite of Passage"
	DarkAdherent              SetItemName = "Dark Adherent"
	Credendum                 SetItemName = "Credendum"
	DangoonsTeaching          SetItemName = "Dangoon's Teaching"
	TaebaeksGlory             SetItemName = "Taebaek's Glory"
	HaemosusAdament           SetItemName = "Haemosu's Adament"
	OndalsAlmighty            SetItemName = "Ondal's Almighty"
	GuillaumesFace            SetItemName = "Guillaume's Face"
	WilhelmsPride             SetItemName = "Wilhelm's Pride"
	MagnusSkin                SetItemName = "Magnus' Skin"
	WihtstansGuard            SetItemName = "Wihtstan's Guard"
	HwaninsSplendor           SetItemName = "Hwanin's Splendor"
	HwaninsRefuge             SetItemName = "Hwanin's Refuge"
	HwaninsBlessing           SetItemName = "Hwanin's Blessing"
	HwaninsJustice            SetItemName = "Hwanin's Justice"
	SazabisCobaltRedeemer     SetItemName = "Sazabi's Cobalt Redeemer"
	SazabisGhostLiberator     SetItemName = "Sazabi's Ghost Liberator"
	SazabisMentalSheath       SetItemName = "Sazabi's Mental Sheath"
	BulKathosSacredCharge     SetItemName = "Bul-Kathos' Sacred Charge"
	BulKathosTribalGuardian   SetItemName = "Bul-Kathos' Tribal Guardian"
	CowKingsHorns             SetItemName = "Cow King's Horns"
	CowKingsHide              SetItemName = "Cow King's Hide"
	CowKingsHoofs             SetItemName = "Cow King's Hoofs"
	NajsPuzzler               SetItemName = "Naj's Puzzler"
	NajsLightPlate            SetItemName = "Naj's Light Plate"
	NajsCirclet               SetItemName = "Naj's Circlet"
	SandersParagon            SetItemName = "Sander's Paragon"
	SandersRiprap             SetItemName = "Sander's Riprap"
	SandersTaboo              SetItemName = "Sander's Taboo"
	SandersSuperstition       SetItemName = "Sander's Superstition"
)

type SetItemInfo struct {
	Name     string
	SetName  string
	Code     string
	LevelReq int
	Rarity   int
	ID       int
}

var SetItems = map[SetItemName]SetItemInfo{
	CiverbsWard:               {Name: "Civerb's Ward", SetName: "Civerb's Vestments", Code: "lrg", LevelReq: 9, Rarity: 7, ID: 0},
	CiverbsIcon:               {Name: "Civerb's Icon", SetName: "Civerb's Vestments", Code: "amu", LevelReq: 9, Rarity: 7, ID: 1},
	CiverbsCudgel:             {Name: "Civerb's Cudgel", SetName: "Civerb's Vestments", Code: "gsc", LevelReq: 9, Rarity: 7, ID: 2},
	HsarusIronHeel:            {Name: "Hsarus' Iron Heel", SetName: "Hsarus' Defense", Code: "mbt", LevelReq: 3, Rarity: 7, ID: 3},
	HsarusIronFist:            {Name: "Hsarus' Iron Fist", SetName: "Hsarus' Defense", Code: "buc", LevelReq: 3, Rarity: 7, ID: 4},
	HsarusIronStay:            {Name: "Hsarus' Iron Stay", SetName: "Hsarus' Defense", Code: "mbl", LevelReq: 3, Rarity: 7, ID: 5},
	CleglawsTooth:             {Name: "Cleglaw's Tooth", SetName: "Cleglaw's Brace", Code: "lsd", LevelReq: 4, Rarity: 7, ID: 6},
	CleglawsClaw:              {Name: "Cleglaw's Claw", SetName: "Cleglaw's Brace", Code: "sml", LevelReq: 4, Rarity: 7, ID: 7},
	CleglawsPincers:           {Name: "Cleglaw's Pincers", SetName: "Cleglaw's Brace", Code: "mgl", LevelReq: 4, Rarity: 7, ID: 8},
	IrathasCollar:             {Name: "Iratha's Collar", SetName: "Iratha's Finery", Code: "amu", LevelReq: 15, Rarity: 7, ID: 9},
	IrathasCuff:               {Name: "Iratha's Cuff", SetName: "Iratha's Finery", Code: "tgl", LevelReq: 15, Rarity: 7, ID: 10},
	IrathasCoil:               {Name: "Iratha's Coil", SetName: "Iratha's Finery", Code: "crn", LevelReq: 15, Rarity: 7, ID: 11},
	IrathasCord:               {Name: "Iratha's Cord", SetName: "Iratha's Finery", Code: "tbl", LevelReq: 15, Rarity: 7, ID: 12},
	IsenhartsLightbrand:       {Name: "Isenhart's Lightbrand", SetName: "Isenhart's Armory", Code: "bsd", LevelReq: 8, Rarity: 7, ID: 13},
	IsenhartsParry:            {Name: "Isenhart's Parry", SetName: "Isenhart's Armory", Code: "gts", LevelReq: 8, Rarity: 7, ID: 14},
	IsenhartsCase:             {Name: "Isenhart's Case", SetName: "Isenhart's Armory", Code: "brs", LevelReq: 8, Rarity: 7, ID: 15},
	IsenhartsHorns:            {Name: "Isenhart's Horns", SetName: "Isenhart's Armory", Code: "fhl", LevelReq: 8, Rarity: 7, ID: 16},
	VidalasBarb:               {Name: "Vidala's Barb", SetName: "Vidala's Rig", Code: "lbb", LevelReq: 14, Rarity: 7, ID: 17},
	VidalasFetlock:            {Name: "Vidala's Fetlock", SetName: "Vidala's Rig", Code: "tbt", LevelReq: 14, Rarity: 7, ID: 18},
	VidalasAmbush:             {Name: "Vidala's Ambush", SetName: "Vidala's Rig", Code: "lea", LevelReq: 14, Rarity: 7, ID: 19},
	VidalasSnare:              {Name: "Vidala's Snare", SetName: "Vidala's Rig", Code: "amu", LevelReq: 14, Rarity: 7, ID: 20},
	MilabregasOrb:             {Name: "Milabrega's Orb", SetName: "Milabrega's Regalia", Code: "kit", LevelReq: 17, Rarity: 7, ID: 21},
	MilabregasRod:             {Name: "Milabrega's Rod", SetName: "Milabrega's Regalia", Code: "wsp", LevelReq: 17, Rarity: 7, ID: 22},
	MilabregasDiadem:          {Name: "Milabrega's Diadem", SetName: "Milabrega's Regalia", Code: "crn", LevelReq: 17, Rarity: 7, ID: 23},
	MilabregasRobe:            {Name: "Milabrega's Robe", SetName: "Milabrega's Regalia", Code: "aar", LevelReq: 17, Rarity: 7, ID: 24},
	CathansRule:               {Name: "Cathan's Rule", SetName: "Cathan's Traps", Code: "bst", LevelReq: 11, Rarity: 7, ID: 25},
	CathansMesh:               {Name: "Cathan's Mesh", SetName: "Cathan's Traps", Code: "chn", LevelReq: 11, Rarity: 7, ID: 26},
	CathansVisage:             {Name: "Cathan's Visage", SetName: "Cathan's Traps", Code: "msk", LevelReq: 11, Rarity: 7, ID: 27},
	CathansSigil:              {Name: "Cathan's Sigil", SetName: "Cathan's Traps", Code: "amu", LevelReq: 11, Rarity: 7, ID: 28},
	CathansSeal:               {Name: "Cathan's Seal", SetName: "Cathan's Traps", Code: "rin", LevelReq: 11, Rarity: 7, ID: 29},
	TancredsCrowbill:          {Name: "Tancred's Crowbill", SetName: "Tancred's Battlegear", Code: "mpi", LevelReq: 20, Rarity: 7, ID: 30},
	TancredsSpine:             {Name: "Tancred's Spine", SetName: "Tancred's Battlegear", Code: "ful", LevelReq: 20, Rarity: 7, ID: 31},
	TancredsHobnails:          {Name: "Tancred's Hobnails", SetName: "Tancred's Battlegear", Code: "lbt", LevelReq: 20, Rarity: 7, ID: 32},
	TancredsWeird:             {Name: "Tancred's Weird", SetName: "Tancred's Battlegear", Code: "amu", LevelReq: 20, Rarity: 7, ID: 33},
	TancredsSkull:             {Name: "Tancred's Skull", SetName: "Tancred's Battlegear", Code: "bhm", LevelReq: 20, Rarity: 7, ID: 34},
	SigonsGage:                {Name: "Sigon's Gage", SetName: "Sigon's Complete Steel", Code: "hgl", LevelReq: 6, Rarity: 7, ID: 35},
	SigonsVisor:               {Name: "Sigon's Visor", SetName: "Sigon's Complete Steel", Code: "ghm", LevelReq: 6, Rarity: 7, ID: 36},
	SigonsShelter:             {Name: "Sigon's Shelter", SetName: "Sigon's Complete Steel", Code: "gth", LevelReq: 6, Rarity: 7, ID: 37},
	SigonsSabot:               {Name: "Sigon's Sabot", SetName: "Sigon's Complete Steel", Code: "hbt", LevelReq: 6, Rarity: 7, ID: 38},
	SigonsWrap:                {Name: "Sigon's Wrap", SetName: "Sigon's Complete Steel", Code: "hbl", LevelReq: 6, Rarity: 7, ID: 39},
	SigonsGuard:               {Name: "Sigon's Guard", SetName: "Sigon's Complete Steel", Code: "tow", LevelReq: 6, Rarity: 7, ID: 40},
	InfernalCranium:           {Name: "Infernal Cranium", SetName: "Infernal Tools", Code: "cap", LevelReq: 5, Rarity: 7, ID: 41},
	InfernalTorch:             {Name: "Infernal Torch", SetName: "Infernal Tools", Code: "gwn", LevelReq: 5, Rarity: 7, ID: 42},
	InfernalSign:              {Name: "Infernal Sign", SetName: "Infernal Tools", Code: "tbl", LevelReq: 5, Rarity: 7, ID: 43},
	BerserkersHeadgear:        {Name: "Berserker's Headgear", SetName: "Berserker's Garb", Code: "hlm", LevelReq: 3, Rarity: 7, ID: 44},
	BerserkersHauberk:         {Name: "Berserker's Hauberk", SetName: "Berserker's Garb", Code: "spl", LevelReq: 3, Rarity: 7, ID: 45},
	BerserkersHatchet:         {Name: "Berserker's Hatchet", SetName: "Berserker's Garb", Code: "2ax", LevelReq: 3, Rarity: 7, ID: 46},
	DeathsHand:                {Name: "Death's Hand", SetName: "Death's Disguise", Code: "lgl", LevelReq: 6, Rarity: 7, ID: 47},
	DeathsGuard:               {Name: "Death's Guard", SetName: "Death's Disguise", Code: "lbl", LevelReq: 6, Rarity: 7, ID: 48},
	DeathsTouch:               {Name: "Death's Touch", SetName: "Death's Disguise", Code: "wsd", LevelReq: 6, Rarity: 7, ID: 49},
	AngelicSickle:             {Name: "Angelic Sickle", SetName: "Angelical Raiment", Code: "sbr", LevelReq: 12, Rarity: 7, ID: 50},
	AngelicMantle:             {Name: "Angelic Mantle", SetName: "Angelical Raiment", Code: "rng", LevelReq: 12, Rarity: 7, ID: 51},
	AngelicHalo:               {Name: "Angelic Halo", SetName: "Angelical Raiment", Code: "rin", LevelReq: 12, Rarity: 3, ID: 52},
	AngelicWings:              {Name: "Angelic Wings", SetName: "Angelical Raiment", Code: "amu", LevelReq: 12, Rarity: 7, ID: 53},
	ArcticHorn:                {Name: "Arctic Horn", SetName: "Arctic Gear", Code: "swb", LevelReq: 2, Rarity: 7, ID: 54},
	ArcticFurs:                {Name: "Arctic Furs", SetName: "Arctic Gear", Code: "qui", LevelReq: 2, Rarity: 7, ID: 55},
	ArcticBinding:             {Name: "Arctic Binding", SetName: "Arctic Gear", Code: "vbl", LevelReq: 2, Rarity: 7, ID: 56},
	ArcticMitts:               {Name: "Arctic Mitts", SetName: "Arctic Gear", Code: "tgl", LevelReq: 2, Rarity: 7, ID: 57},
	ArcannasSign:              {Name: "Arcanna's Sign", SetName: "Arcanna's Tricks", Code: "amu", LevelReq: 15, Rarity: 1, ID: 58},
	ArcannasDeathwand:         {Name: "Arcanna's Deathwand", SetName: "Arcanna's Tricks", Code: "wst", LevelReq: 15, Rarity: 7, ID: 59},
	ArcannasHead:              {Name: "Arcanna's Head", SetName: "Arcanna's Tricks", Code: "skp", LevelReq: 15, Rarity: 7, ID: 60},
	ArcannasFlesh:             {Name: "Arcanna's Flesh", SetName: "Arcanna's Tricks", Code: "ltp", LevelReq: 15, Rarity: 7, ID: 61},
	NatalyasTotem:             {Name: "Natalya's Totem", SetName: "Natalya's Odium", Code: "xh9", LevelReq: 59, Rarity: 7, ID: 62},
	NatalyasMark:              {Name: "Natalya's Mark", SetName: "Natalya's Odium", Code: "7qr", LevelReq: 79, Rarity: 7, ID: 63},
	NatalyasShadow:            {Name: "Natalya's Shadow", SetName: "Natalya's Odium", Code: "ucl", LevelReq: 73, Rarity: 7, ID: 64},
	NatalyasSoul:              {Name: "Natalya's Soul", SetName: "Natalya's Odium", Code: "xmb", LevelReq: 25, Rarity: 7, ID: 65},
	AldursStonyGaze:           {Name: "Aldur's Stony Gaze", SetName: "Aldur's Watchtower", Code: "dr8", LevelReq: 36, Rarity: 7, ID: 66},
	AldursDeception:           {Name: "Aldur's Deception", SetName: "Aldur's Watchtower", Code: "uul", LevelReq: 76, Rarity: 7, ID: 67},
	AldursRhythm:              {Name: "Aldur's Rhythm", SetName: "Aldur's Watchtower", Code: "9mt", LevelReq: 42, Rarity: 7, ID: 68},
	AldursAdvance:             {Name: "Aldur's Advance", SetName: "Aldur's Watchtower", Code: "xtb", LevelReq: 45, Rarity: 7, ID: 69},
	ImmortalKingsWill:         {Name: "Immortal King's Will", SetName: "Immortal King", Code: "ba5", LevelReq: 47, Rarity: 7, ID: 70},
	ImmortalKingsSoulCage:     {Name: "Immortal King's Soul Cage", SetName: "Immortal King", Code: "uar", LevelReq: 76, Rarity: 7, ID: 71},
	ImmortalKingsDetail:       {Name: "Immortal King's Detail", SetName: "Immortal King", Code: "zhb", LevelReq: 29, Rarity: 7, ID: 72},
	ImmortalKingsForge:        {Name: "Immortal King's Forge", SetName: "Immortal King", Code: "xhg", LevelReq: 30, Rarity: 7, ID: 73},
	ImmortalKingsPillar:       {Name: "Immortal King's Pillar", SetName: "Immortal King", Code: "xhb", LevelReq: 31, Rarity: 7, ID: 74},
	ImmortalKingsStoneCrusher: {Name: "Immortal King's Stone Crusher", SetName: "Immortal King", Code: "7m7", LevelReq: 76, Rarity: 7, ID: 75},
	TalRashasFireSpunCloth:    {Name: "Tal Rasha's Fire-Spun Cloth", SetName: "Tal Rasha's Wrappings", Code: "zmb", LevelReq: 53, Rarity: 7, ID: 76},
	TalRashasAdjudication:     {Name: "Tal Rasha's Adjudication", SetName: "Tal Rasha's Wrappings", Code: "amu", LevelReq: 67, Rarity: 1, ID: 77},
	TalRashasLidlessEye:       {Name: "Tal Rasha's Lidless Eye", SetName: "Tal Rasha's Wrappings", Code: "oba", LevelReq: 65, Rarity: 7, ID: 78},
	TalRashasGuardianship:     {Name: "Tal Rasha's Guardianship", SetName: "Tal Rasha's Wrappings", Code: "uth", LevelReq: 71, Rarity: 7, ID: 79},
	TalRashasHoradricCrest:    {Name: "Tal Rasha's Horadric Crest", SetName: "Tal Rasha's Wrappings", Code: "xsk", LevelReq: 66, Rarity: 7, ID: 80},
	GriswoldsValor:            {Name: "Griswold's Valor", SetName: "Griswold's Legacy", Code: "urn", LevelReq: 69, Rarity: 7, ID: 81},
	GriswoldsHeart:            {Name: "Griswold's Heart", SetName: "Griswold's Legacy", Code: "xar", LevelReq: 45, Rarity: 7, ID: 82},
	GriswoldssRedemption:      {Name: "Griswolds's Redemption", SetName: "Griswold's Legacy", Code: "7ws", LevelReq: 53, Rarity: 7, ID: 83},
	GriswoldsHonor:            {Name: "Griswold's Honor", SetName: "Griswold's Legacy", Code: "paf", LevelReq: 68, Rarity: 7, ID: 84},
	TrangOulsGuise:            {Name: "Trang-Oul's Guise", SetName: "Trang-Oul's Avatar", Code: "uh9", LevelReq: 65, Rarity: 7, ID: 85},
	TrangOulsScales:           {Name: "Trang-Oul's Scales", SetName: "Trang-Oul's Avatar", Code: "xul", LevelReq: 49, Rarity: 7, ID: 86},
	TrangOulsWing:             {Name: "Trang-Oul's Wing", SetName: "Trang-Oul's Avatar", Code: "ne9", LevelReq: 54, Rarity: 7, ID: 87},
	TrangOulsClaws:            {Name: "Trang-Oul's Claws", SetName: "Trang-Oul's Avatar", Code: "xmg", LevelReq: 45, Rarity: 7, ID: 88},
	TrangOulsGirth:            {Name: "Trang-Oul's Girth", SetName: "Trang-Oul's Avatar", Code: "utc", LevelReq: 47, Rarity: 7, ID: 89},
	MavinasTrueSight:          {Name: "M'avina's True Sight", SetName: "M'avina's Battle Hymn", Code: "ci3", LevelReq: 59, Rarity: 7, ID: 90},
	MavinasEmbrace:            {Name: "M'avina's Embrace", SetName: "M'avina's Battle Hymn", Code: "uld", LevelReq: 70, Rarity: 7, ID: 91},
	MavinasIcyClutch:          {Name: "M'avina's Icy Clutch", SetName: "M'avina's Battle Hymn", Code: "xtg", LevelReq: 32, Rarity: 7, ID: 92},
	MavinasTenet:              {Name: "M'avina's Tenet", SetName: "M'avina's Battle Hymn", Code: "zvb", LevelReq: 45, Rarity: 7, ID: 93},
	MavinasCaster:             {Name: "M'avina's Caster", SetName: "M'avina's Battle Hymn", Code: "amc", LevelReq: 70, Rarity: 7, ID: 94},
	TellingofBeads:            {Name: "Telling of Beads", SetName: "The Disciple", Code: "amu", LevelReq: 30, Rarity: 1, ID: 95},
	LayingofHands:             {Name: "Laying of Hands", SetName: "The Disciple", Code: "ulg", LevelReq: 63, Rarity: 7, ID: 96},
	RiteofPassage:             {Name: "Rite of Passage", SetName: "The Disciple", Code: "xlb", LevelReq: 29, Rarity: 7, ID: 97},
	DarkAdherent:              {Name: "Dark Adherent", SetName: "The Disciple", Code: "uui", LevelReq: 43, Rarity: 7, ID: 98},
	Credendum:                 {Name: "Credendum", SetName: "The Disciple", Code: "umc", LevelReq: 65, Rarity: 7, ID: 99},
	DangoonsTeaching:          {Name: "Dangoon's Teaching", SetName: "Heaven's Brethren", Code: "7ma", LevelReq: 68, Rarity: 7, ID: 100},
	TaebaeksGlory:             {Name: "Taebaek's Glory", SetName: "Heaven's Brethren", Code: "uts", LevelReq: 81, Rarity: 7, ID: 101},
	HaemosusAdament:           {Name: "Haemosu's Adament", SetName: "Heaven's Brethren", Code: "xrs", LevelReq: 44, Rarity: 7, ID: 102},
	OndalsAlmighty:            {Name: "Ondal's Almighty", SetName: "Heaven's Brethren", Code: "uhm", LevelReq: 69, Rarity: 7, ID: 103},
	GuillaumesFace:            {Name: "Guillaume's Face", SetName: "Orphan's Call", Code: "xhm", LevelReq: 34, Rarity: 7, ID: 104},
	WilhelmsPride:             {Name: "Wilhelm's Pride", SetName: "Orphan's Call", Code: "ztb", LevelReq: 42, Rarity: 7, ID: 105},
	MagnusSkin:                {Name: "Magnus' Skin", SetName: "Orphan's Call", Code: "xvg", LevelReq: 37, Rarity: 7, ID: 106},
	WihtstansGuard:            {Name: "Wihtstan's Guard", SetName: "Orphan's Call", Code: "xml", LevelReq: 29, Rarity: 7, ID: 107},
	HwaninsSplendor:           {Name: "Hwanin's Splendor", SetName: "Hwanin's Majesty", Code: "xrn", LevelReq: 45, Rarity: 7, ID: 108},
	HwaninsRefuge:             {Name: "Hwanin's Refuge", SetName: "Hwanin's Majesty", Code: "xcl", LevelReq: 30, Rarity: 7, ID: 109},
	HwaninsBlessing:           {Name: "Hwanin's Blessing", SetName: "Hwanin's Majesty", Code: "mbl", LevelReq: 35, Rarity: 7, ID: 110},
	HwaninsJustice:            {Name: "Hwanin's Justice", SetName: "Hwanin's Majesty", Code: "9vo", LevelReq: 28, Rarity: 7, ID: 111},
	SazabisCobaltRedeemer:     {Name: "Sazabi's Cobalt Redeemer", SetName: "Sazabi's Grand Tribute", Code: "7ls", LevelReq: 73, Rarity: 7, ID: 112},
	SazabisGhostLiberator:     {Name: "Sazabi's Ghost Liberator", SetName: "Sazabi's Grand Tribute", Code: "upl", LevelReq: 67, Rarity: 7, ID: 113},
	SazabisMentalSheath:       {Name: "Sazabi's Mental Sheath", SetName: "Sazabi's Grand Tribute", Code: "xhl", LevelReq: 43, Rarity: 7, ID: 114},
	BulKathosSacredCharge:     {Name: "Bul-Kathos' Sacred Charge", SetName: "Bul-Kathos' Children", Code: "7gd", LevelReq: 61, Rarity: 7, ID: 115},
	BulKathosTribalGuardian:   {Name: "Bul-Kathos' Tribal Guardian", SetName: "Bul-Kathos' Children", Code: "7wd", LevelReq: 54, Rarity: 7, ID: 116},
	CowKingsHorns:             {Name: "Cow King's Horns", SetName: "Cow King's Leathers", Code: "xap", LevelReq: 25, Rarity: 7, ID: 117},
	CowKingsHide:              {Name: "Cow King's Hide", SetName: "Cow King's Leathers", Code: "stu", LevelReq: 18, Rarity: 7, ID: 118},
	CowKingsHoofs:             {Name: "Cow King's Hoofs", SetName: "Cow King's Leathers", Code: "vbt", LevelReq: 13, Rarity: 7, ID: 119},
	NajsPuzzler:               {Name: "Naj's Puzzler", SetName: "Naj's Ancient Set", Code: "6cs", LevelReq: 78, Rarity: 7, ID: 120},
	NajsLightPlate:            {Name: "Naj's Light Plate", SetName: "Naj's Ancient Set", Code: "ult", LevelReq: 71, Rarity: 7, ID: 121},
	NajsCirclet:               {Name: "Naj's Circlet", SetName: "Naj's Ancient Set", Code: "ci0", LevelReq: 28, Rarity: 7, ID: 122},
	SandersParagon:            {Name: "Sander's Paragon", SetName: "Sander's Folly", Code: "cap", LevelReq: 25, Rarity: 3, ID: 123},
	SandersRiprap:             {Name: "Sander's Riprap", SetName: "Sander's Folly", Code: "vbt", LevelReq: 20, Rarity: 7, ID: 124},
	SandersTaboo:              {Name: "Sander's Taboo", SetName: "Sander's Folly", Code: "vgl", LevelReq: 28, Rarity: 7, ID: 125},
	SandersSuperstition:       {Name: "Sander's Superstition", SetName: "Sander's Folly", Code: "bwn", LevelReq: 25, Rarity: 7, ID: 126},
}

var Sets = map[string][]SetItemName{
	"Civerb's Vestments": {
		CiverbsWard,
		CiverbsIcon,
		CiverbsCudgel,
	},
	"Hsarus' Defense": {
		HsarusIronHeel,
		HsarusIronFist,
		HsarusIronStay,
	},
	"Cleglaw's Brace": {
		CleglawsTooth,
		CleglawsClaw,
		CleglawsPincers,
	},
	"Iratha's Finery": {
		IrathasCollar,
		IrathasCuff,
		IrathasCoil,
		IrathasCord,
	},
	"Isenhart's Armory": {
		IsenhartsLightbrand,
		IsenhartsParry,
		IsenhartsCase,
		IsenhartsHorns,
	},
	"Vidala's Rig": {
		VidalasBarb,
		VidalasFetlock,
		VidalasAmbush,
		VidalasSnare,
	},
	"Milabrega's Regalia": {
		MilabregasOrb,
		MilabregasRod,
		MilabregasDiadem,
		MilabregasRobe,
	},
	"Cathan's Traps": {
		CathansRule,
		CathansMesh,
		CathansVisage,
		CathansSigil,
		CathansSeal,
	},
	"Tancred's Battlegear": {
		TancredsCrowbill,
		TancredsSpine,
		TancredsHobnails,
		TancredsWeird,
		TancredsSkull,
	},
	"Sigon's Complete Steel": {
		SigonsGage,
		SigonsVisor,
		SigonsShelter,
		SigonsSabot,
		SigonsWrap,
		SigonsGuard,
	},
	"Infernal Tools": {
		InfernalCranium,
		InfernalTorch,
		InfernalSign,
	},
	"Berserker's Garb": {
		BerserkersHeadgear,
		BerserkersHauberk,
		BerserkersHatchet,
	},
	"Death's Disguise": {
		DeathsHand,
		DeathsGuard,
		DeathsTouch,
	},
	"Angelical Raiment": {
		AngelicSickle,
		AngelicMantle,
		AngelicHalo,
		AngelicWings,
	},
	"Arctic Gear": {
		ArcticHorn,
		ArcticFurs,
		ArcticBinding,
		ArcticMitts,
	},
	"Arcanna's Tricks": {
		ArcannasSign,
		ArcannasDeathwand,
		ArcannasHead,
		ArcannasFlesh,
	},
	"Natalya's Odium": {
		NatalyasTotem,
		NatalyasMark,
		NatalyasShadow,
		NatalyasSoul,
	},
	"Aldur's Watchtower": {
		AldursStonyGaze,
		AldursDeception,
		AldursRhythm,
		AldursAdvance,
	},
	"Immortal King": {
		ImmortalKingsWill,
		ImmortalKingsSoulCage,
		ImmortalKingsDetail,
		ImmortalKingsForge,
		ImmortalKingsPillar,
		ImmortalKingsStoneCrusher,
	},
	"Tal Rasha's Wrappings": {
		TalRashasFireSpunCloth,
		TalRashasAdjudication,
		TalRashasLidlessEye,
		TalRashasGuardianship,
		TalRashasHoradricCrest,
	},
	"Griswold's Legacy": {
		GriswoldsValor,
		GriswoldsHeart,
		GriswoldssRedemption,
		GriswoldsHonor,
	},
	"Trang-Oul's Avatar": {
		TrangOulsGuise,
		TrangOulsScales,
		TrangOulsWing,
		TrangOulsClaws,
		TrangOulsGirth,
	},
	"M'avina's Battle Hymn": {
		MavinasTrueSight,
		MavinasEmbrace,
		MavinasIcyClutch,
		MavinasTenet,
		MavinasCaster,
	},
	"The Disciple": {
		TellingofBeads,
		LayingofHands,
		RiteofPassage,
		DarkAdherent,
		Credendum,
	},
	"Heaven's Brethren": {
		DangoonsTeaching,
		TaebaeksGlory,
		HaemosusAdament,
		OndalsAlmighty,
	},
	"Orphan's Call": {
		GuillaumesFace,
		WilhelmsPride,
		MagnusSkin,
		WihtstansGuard,
	},
	"Hwanin's Majesty": {
		HwaninsSplendor,
		HwaninsRefuge,
		HwaninsBlessing,
		HwaninsJustice,
	},
	"Sazabi's Grand Tribute": {
		SazabisCobaltRedeemer,
		SazabisGhostLiberator,
		SazabisMentalSheath,
	},
	"Bul-Kathos' Children": {
		BulKathosSacredCharge,
		BulKathosTribalGuardian,
	},
	"Cow King's Leathers": {
		CowKingsHorns,
		CowKingsHide,
		CowKingsHoofs,
	},
	"Naj's Ancient Set": {
		NajsPuzzler,
		NajsLightPlate,
		NajsCirclet,
	},
	"Sander's Folly": {
		SandersParagon,
		SandersRiprap,
		SandersTaboo,
		SandersSuperstition,
	},
}
