// Code generated by cmd/txttocode. DO NOT EDIT.
// source: cmd/txttocode/txt/uniqueitems.txt
package item

type UniqueName string

const (
	None                            UniqueName = ""
	TheGnasher                      UniqueName = "The Gnasher"
	Deathspade                      UniqueName = "Deathspade"
	Bladebone                       UniqueName = "Bladebone"
	Mindrend                        UniqueName = "Mindrend"
	Rakescar                        UniqueName = "Rakescar"
	FechmarsAxe                     UniqueName = "Fechmars Axe"
	Goreshovel                      UniqueName = "Goreshovel"
	TheChieftan                     UniqueName = "The Chieftan"
	Brainhew                        UniqueName = "Brainhew"
	TheHumongous                    UniqueName = "The Humongous"
	IrosTorch                       UniqueName = "Iros Torch"
	Maelstromwrath                  UniqueName = "Maelstromwrath"
	Gravenspine                     UniqueName = "Gravenspine"
	UmesLament                      UniqueName = "Umes Lament"
	Felloak                         UniqueName = "Felloak"
	KnellStriker                    UniqueName = "Knell Striker"
	Rusthandle                      UniqueName = "Rusthandle"
	Stormeye                        UniqueName = "Stormeye"
	Stoutnail                       UniqueName = "Stoutnail"
	Crushflange                     UniqueName = "Crushflange"
	Bloodrise                       UniqueName = "Bloodrise"
	TheGeneralsTanDoLiGa            UniqueName = "The Generals Tan Do Li Ga"
	Ironstone                       UniqueName = "Ironstone"
	Bonesob                         UniqueName = "Bonesob"
	Steeldriver                     UniqueName = "Steeldriver"
	RixotsKeen                      UniqueName = "Rixots Keen"
	BloodCrescent                   UniqueName = "Blood Crescent"
	KrintizsSkewer                  UniqueName = "Krintizs Skewer"
	Gleamscythe                     UniqueName = "Gleamscythe"
	GriswoldsEdge                   UniqueName = "Griswolds Edge"
	Hellplague                      UniqueName = "Hellplague"
	CulwensPoint                    UniqueName = "Culwens Point"
	Shadowfang                      UniqueName = "Shadowfang"
	Soulflay                        UniqueName = "Soulflay"
	KinemilsAwl                     UniqueName = "Kinemils Awl"
	Blacktongue                     UniqueName = "Blacktongue"
	Ripsaw                          UniqueName = "Ripsaw"
	ThePatriarch                    UniqueName = "The Patriarch"
	Gull                            UniqueName = "Gull"
	TheDiggler                      UniqueName = "The Diggler"
	TheJadeTanDo                    UniqueName = "The Jade Tan Do"
	IricesShard                     UniqueName = "Irices Shard"
	TheDragonChang                  UniqueName = "The Dragon Chang"
	Razortine                       UniqueName = "Razortine"
	Bloodthief                      UniqueName = "Bloodthief"
	LanceofYaggai                   UniqueName = "Lance of Yaggai"
	TheTannrGorerod                 UniqueName = "The Tannr Gorerod"
	DimoaksHew                      UniqueName = "Dimoaks Hew"
	Steelgoad                       UniqueName = "Steelgoad"
	SoulHarvest                     UniqueName = "Soul Harvest"
	TheBattlebranch                 UniqueName = "The Battlebranch"
	Woestave                        UniqueName = "Woestave"
	TheGrimReaper                   UniqueName = "The Grim Reaper"
	BaneAsh                         UniqueName = "Bane Ash"
	SerpentLord                     UniqueName = "Serpent Lord"
	LazarusSpire                    UniqueName = "Lazarus Spire"
	TheSalamander                   UniqueName = "The Salamander"
	TheIronJangBong                 UniqueName = "The Iron Jang Bong"
	Pluckeye                        UniqueName = "Pluckeye"
	Witherstring                    UniqueName = "Witherstring"
	Rimeraven                       UniqueName = "Rimeraven"
	Piercerib                       UniqueName = "Piercerib"
	Pullspite                       UniqueName = "Pullspite"
	Wizendraw                       UniqueName = "Wizendraw"
	Hellclap                        UniqueName = "Hellclap"
	Blastbark                       UniqueName = "Blastbark"
	Leadcrow                        UniqueName = "Leadcrow"
	Ichorsting                      UniqueName = "Ichorsting"
	Hellcast                        UniqueName = "Hellcast"
	Doomspittle                     UniqueName = "Doomspittle"
	WarBonnet                       UniqueName = "War Bonnet"
	Tarnhelm                        UniqueName = "Tarnhelm"
	CoifofGlory                     UniqueName = "Coif of Glory"
	Duskdeep                        UniqueName = "Duskdeep"
	Wormskull                       UniqueName = "Wormskull"
	Howltusk                        UniqueName = "Howltusk"
	UndeadCrown                     UniqueName = "Undead Crown"
	TheFaceofHorror                 UniqueName = "The Face of Horror"
	Greyform                        UniqueName = "Greyform"
	BlinkbatsForm                   UniqueName = "Blinkbats Form"
	TheCenturion                    UniqueName = "The Centurion"
	Twitchthroe                     UniqueName = "Twitchthroe"
	Darkglow                        UniqueName = "Darkglow"
	Hawkmail                        UniqueName = "Hawkmail"
	SparkingMail                    UniqueName = "Sparking Mail"
	Venomsward                      UniqueName = "Venomsward"
	Iceblink                        UniqueName = "Iceblink"
	Boneflesh                       UniqueName = "Boneflesh"
	Rockfleece                      UniqueName = "Rockfleece"
	Rattlecage                      UniqueName = "Rattlecage"
	Goldskin                        UniqueName = "Goldskin"
	VictorsSilk                     UniqueName = "Victors Silk"
	HeavenlyGarb                    UniqueName = "Heavenly Garb"
	PeltaLunata                     UniqueName = "Pelta Lunata"
	UmbralDisk                      UniqueName = "Umbral Disk"
	Stormguild                      UniqueName = "Stormguild"
	WalloftheEyeless                UniqueName = "Wall of the Eyeless"
	SwordbackHold                   UniqueName = "Swordback Hold"
	Steelclash                      UniqueName = "Steelclash"
	BverritKeep                     UniqueName = "Bverrit Keep"
	TheWard                         UniqueName = "The Ward"
	TheHandofBroc                   UniqueName = "The Hand of Broc"
	Bloodfist                       UniqueName = "Bloodfist"
	ChanceGuards                    UniqueName = "Chance Guards"
	Magefist                        UniqueName = "Magefist"
	Frostburn                       UniqueName = "Frostburn"
	Hotspur                         UniqueName = "Hotspur"
	Gorefoot                        UniqueName = "Gorefoot"
	TreadsofCthon                   UniqueName = "Treads of Cthon"
	GoblinToe                       UniqueName = "Goblin Toe"
	Tearhaunch                      UniqueName = "Tearhaunch"
	LenymsCord                      UniqueName = "Lenyms Cord"
	Snakecord                       UniqueName = "Snakecord"
	Nightsmoke                      UniqueName = "Nightsmoke"
	Goldwrap                        UniqueName = "Goldwrap"
	Bladebuckle                     UniqueName = "Bladebuckle"
	NokozanRelic                    UniqueName = "Nokozan Relic"
	TheEyeofEtlich                  UniqueName = "The Eye of Etlich"
	TheMahimOakCurio                UniqueName = "The Mahim-Oak Curio"
	Nagelring                       UniqueName = "Nagelring"
	ManaldHeal                      UniqueName = "Manald Heal"
	TheStoneofJordan                UniqueName = "The Stone of Jordan"
	AmuletoftheViper                UniqueName = "Amulet of the Viper"
	StaffofKings                    UniqueName = "Staff of Kings"
	HoradricStaff                   UniqueName = "Horadric Staff"
	HellForgeHammer                 UniqueName = "Hell Forge Hammer"
	KhalimFlail                     UniqueName = "KhalimFlail"
	SuperKhalimFlail                UniqueName = "SuperKhalimFlail"
	Coldkill                        UniqueName = "Coldkill"
	ButchersPupil                   UniqueName = "Butcher's Pupil"
	Islestrike                      UniqueName = "Islestrike"
	PompesWrath                     UniqueName = "Pompe's Wrath"
	GuardianNaga                    UniqueName = "Guardian Naga"
	WarlordsTrust                   UniqueName = "Warlord's Trust"
	Spellsteel                      UniqueName = "Spellsteel"
	Stormrider                      UniqueName = "Stormrider"
	BoneslayerBlade                 UniqueName = "Boneslayer Blade"
	TheMinataur                     UniqueName = "The Minataur"
	SuicideBranch                   UniqueName = "Suicide Branch"
	CarinShard                      UniqueName = "Carin Shard"
	ArmofKingLeoric                 UniqueName = "Arm of King Leoric"
	BlackhandKey                    UniqueName = "Blackhand Key"
	DarkClanCrusher                 UniqueName = "Dark Clan Crusher"
	ZakarumsHand                    UniqueName = "Zakarum's Hand"
	TheFetidSprinkler               UniqueName = "The Fetid Sprinkler"
	HandofBlessedLight              UniqueName = "Hand of Blessed Light"
	Fleshrender                     UniqueName = "Fleshrender"
	SureshrillFrost                 UniqueName = "Sureshrill Frost"
	Moonfall                        UniqueName = "Moonfall"
	BaezilsVortex                   UniqueName = "Baezil's Vortex"
	Earthshaker                     UniqueName = "Earthshaker"
	BloodtreeStump                  UniqueName = "Bloodtree Stump"
	TheGavelofPain                  UniqueName = "The Gavel of Pain"
	Bloodletter                     UniqueName = "Bloodletter"
	ColdsteelEye                    UniqueName = "Coldsteel Eye"
	Hexfire                         UniqueName = "Hexfire"
	BladeofAliBaba                  UniqueName = "Blade of Ali Baba"
	GinthersRift                    UniqueName = "Ginther's Rift"
	Headstriker                     UniqueName = "Headstriker"
	PlagueBearer                    UniqueName = "Plague Bearer"
	TheAtlantian                    UniqueName = "The Atlantian"
	CrainteVomir                    UniqueName = "Crainte Vomir"
	BingSzWang                      UniqueName = "Bing Sz Wang"
	TheVileHusk                     UniqueName = "The Vile Husk"
	Cloudcrack                      UniqueName = "Cloudcrack"
	TodesfaelleFlamme               UniqueName = "Todesfaelle Flamme"
	Swordguard                      UniqueName = "Swordguard"
	Spineripper                     UniqueName = "Spineripper"
	HeartCarver                     UniqueName = "Heart Carver"
	BlackbogsSharp                  UniqueName = "Blackbog's Sharp"
	Stormspike                      UniqueName = "Stormspike"
	TheImpaler                      UniqueName = "The Impaler"
	KelpieSnare                     UniqueName = "Kelpie Snare"
	SoulfeastTine                   UniqueName = "Soulfeast Tine"
	HoneSundan                      UniqueName = "Hone Sundan"
	SpireofHonor                    UniqueName = "Spire of Honor"
	TheMeatScraper                  UniqueName = "The Meat Scraper"
	BlackleachBlade                 UniqueName = "Blackleach Blade"
	AthenasWrath                    UniqueName = "Athena's Wrath"
	PierreTombaleCouant             UniqueName = "Pierre Tombale Couant"
	HusoldalEvo                     UniqueName = "Husoldal Evo"
	GrimsBurningDead                UniqueName = "Grim's Burning Dead"
	Razorswitch                     UniqueName = "Razorswitch"
	Ribcracker                      UniqueName = "Ribcracker"
	ChromaticIre                    UniqueName = "Chromatic Ire"
	Warpspear                       UniqueName = "Warpspear"
	Skullcollector                  UniqueName = "Skullcollector"
	Skystrike                       UniqueName = "Skystrike"
	Riphook                         UniqueName = "Riphook"
	KukoShakaku                     UniqueName = "Kuko Shakaku"
	Endlesshail                     UniqueName = "Endlesshail"
	WhichwildString                 UniqueName = "Whichwild String"
	Cliffkiller                     UniqueName = "Cliffkiller"
	Magewrath                       UniqueName = "Magewrath"
	GodstrikeArch                   UniqueName = "Godstrike Arch"
	LangerBriser                    UniqueName = "Langer Briser"
	PusSpiter                       UniqueName = "Pus Spiter"
	BurizaDoKyanon                  UniqueName = "Buriza-Do Kyanon"
	DemonMachine                    UniqueName = "Demon Machine"
	PeasentCrown                    UniqueName = "Peasent Crown"
	Rockstopper                     UniqueName = "Rockstopper"
	Stealskull                      UniqueName = "Stealskull"
	DarksightHelm                   UniqueName = "Darksight Helm"
	ValkiryWing                     UniqueName = "Valkiry Wing"
	CrownofThieves                  UniqueName = "Crown of Thieves"
	BlackhornsFace                  UniqueName = "Blackhorn's Face"
	Vampiregaze                     UniqueName = "Vampiregaze"
	TheSpiritShroud                 UniqueName = "The Spirit Shroud"
	SkinoftheVipermagi              UniqueName = "Skin of the Vipermagi"
	SkinoftheFlayerdOne             UniqueName = "Skin of the Flayerd One"
	Ironpelt                        UniqueName = "Ironpelt"
	Spiritforge                     UniqueName = "Spiritforge"
	CrowCaw                         UniqueName = "Crow Caw"
	Shaftstop                       UniqueName = "Shaftstop"
	DurielsShell                    UniqueName = "Duriel's Shell"
	SkulldersIre                    UniqueName = "Skullder's Ire"
	GuardianAngel                   UniqueName = "Guardian Angel"
	Toothrow                        UniqueName = "Toothrow"
	AtmasWail                       UniqueName = "Atma's Wail"
	BlackHades                      UniqueName = "Black Hades"
	Corpsemourn                     UniqueName = "Corpsemourn"
	QueHegansWisdon                 UniqueName = "Que-Hegan's Wisdon"
	Visceratuant                    UniqueName = "Visceratuant"
	MosersBlessedCircle             UniqueName = "Mosers Blessed Circle"
	Stormchaser                     UniqueName = "Stormchaser"
	TiamatsRebuke                   UniqueName = "Tiamat's Rebuke"
	KerkesSanctuary                 UniqueName = "Kerke's Sanctuary"
	RadimantsSphere                 UniqueName = "Radimant's Sphere"
	LidlessWall                     UniqueName = "Lidless Wall"
	LanceGuard                      UniqueName = "Lance Guard"
	VenomGrip                       UniqueName = "Venom Grip"
	Gravepalm                       UniqueName = "Gravepalm"
	Ghoulhide                       UniqueName = "Ghoulhide"
	Lavagout                        UniqueName = "Lavagout"
	Hellmouth                       UniqueName = "Hellmouth"
	Infernostride                   UniqueName = "Infernostride"
	Waterwalk                       UniqueName = "Waterwalk"
	Silkweave                       UniqueName = "Silkweave"
	Wartraveler                     UniqueName = "Wartraveler"
	Gorerider                       UniqueName = "Gorerider"
	StringofEars                    UniqueName = "String of Ears"
	Razortail                       UniqueName = "Razortail"
	Gloomstrap                      UniqueName = "Gloomstrap"
	Snowclash                       UniqueName = "Snowclash"
	ThudergodsVigor                 UniqueName = "Thudergod's Vigor"
	HarlequinCrest                  UniqueName = "Harlequin Crest"
	VeilofSteel                     UniqueName = "Veil of Steel"
	TheGladiatorsBane               UniqueName = "The Gladiator's Bane"
	ArkainesValor                   UniqueName = "Arkaine's Valor"
	BlackoakShield                  UniqueName = "Blackoak Shield"
	Stormshield                     UniqueName = "Stormshield"
	Hellslayer                      UniqueName = "Hellslayer"
	MesserschmidtsReaver            UniqueName = "Messerschmidt's Reaver"
	BaranarsStar                    UniqueName = "Baranar's Star"
	SchaefersHammer                 UniqueName = "Schaefer's Hammer"
	TheCraniumBasher                UniqueName = "The Cranium Basher"
	Lightsabre                      UniqueName = "Lightsabre"
	Doombringer                     UniqueName = "Doombringer"
	TheGrandfather                  UniqueName = "The Grandfather"
	Wizardspike                     UniqueName = "Wizardspike"
	Stormspire                      UniqueName = "Stormspire"
	Eaglehorn                       UniqueName = "Eaglehorn"
	Windforce                       UniqueName = "Windforce"
	BulKathosWeddingBand            UniqueName = "Bul Katho's Wedding Band"
	TheCatsEye                      UniqueName = "The Cat's Eye"
	TheRisingSun                    UniqueName = "The Rising Sun"
	CrescentMoon                    UniqueName = "Crescent Moon"
	MarasKaleidoscope               UniqueName = "Mara's Kaleidoscope"
	AtmasScarab                     UniqueName = "Atma's Scarab"
	DwarfStar                       UniqueName = "Dwarf Star"
	RavenFrost                      UniqueName = "Raven Frost"
	HighlordsWrath                  UniqueName = "Highlord's Wrath"
	SaracensChance                  UniqueName = "Saracen's Chance"
	ArreatsFace                     UniqueName = "Arreat's Face"
	Homunculus                      UniqueName = "Homunculus"
	TitansRevenge                   UniqueName = "Titan's Revenge"
	LycandersAim                    UniqueName = "Lycander's Aim"
	LycandersFlank                  UniqueName = "Lycander's Flank"
	TheOculus                       UniqueName = "The Oculus"
	HeraldofZakarum                 UniqueName = "Herald of Zakarum"
	Cutthroat1                      UniqueName = "Cutthroat1"
	JalalsMane                      UniqueName = "Jalal's Mane"
	TheScalper                      UniqueName = "The Scalper"
	Bloodmoon                       UniqueName = "Bloodmoon"
	Djinnslayer                     UniqueName = "Djinnslayer"
	Deathbit                        UniqueName = "Deathbit"
	Warshrike                       UniqueName = "Warshrike"
	Gutsiphon                       UniqueName = "Gutsiphon"
	Razoredge                       UniqueName = "Razoredge"
	Demonlimb                       UniqueName = "Demonlimb"
	Steelshade                      UniqueName = "Steelshade"
	TombReaver                      UniqueName = "Tomb Reaver"
	DeathssWeb                      UniqueName = "Deaths's Web"
	NaturesPeace                    UniqueName = "Nature's Peace"
	Azurewrath                      UniqueName = "Azurewrath"
	SeraphsHymn                     UniqueName = "Seraph's Hymn"
	Fleshripper                     UniqueName = "Fleshripper"
	HorizonsTornado                 UniqueName = "Horizon's Tornado"
	StoneCrusher                    UniqueName = "Stone Crusher"
	Jadetalon                       UniqueName = "Jadetalon"
	Shadowdancer                    UniqueName = "Shadowdancer"
	Cerebus                         UniqueName = "Cerebus"
	TyraelsMight                    UniqueName = "Tyrael's Might"
	Souldrain                       UniqueName = "Souldrain"
	Runemaster                      UniqueName = "Runemaster"
	Deathcleaver                    UniqueName = "Deathcleaver"
	ExecutionersJustice             UniqueName = "Executioner's Justice"
	Stoneraven                      UniqueName = "Stoneraven"
	Leviathan                       UniqueName = "Leviathan"
	Wisp                            UniqueName = "Wisp"
	GargoylesBite                   UniqueName = "Gargoyle's Bite"
	Lacerator                       UniqueName = "Lacerator"
	MangSongsLesson                 UniqueName = "Mang Song's Lesson"
	Viperfork                       UniqueName = "Viperfork"
	EtherealEdge                    UniqueName = "Ethereal Edge"
	DemonhornsEdge                  UniqueName = "Demonhorn's Edge"
	TheReapersToll                  UniqueName = "The Reaper's Toll"
	Spiritkeeper                    UniqueName = "Spiritkeeper"
	Hellrack                        UniqueName = "Hellrack"
	AlmaNegra                       UniqueName = "Alma Negra"
	DarkforgeSpawn                  UniqueName = "Darkforge Spawn"
	Widowmaker                      UniqueName = "Widowmaker"
	BloodravensCharge               UniqueName = "Bloodraven's Charge"
	Ghostflame                      UniqueName = "Ghostflame"
	Shadowkiller                    UniqueName = "Shadowkiller"
	Gimmershred                     UniqueName = "Gimmershred"
	GriffonsEye                     UniqueName = "Griffon's Eye"
	Windhammer                      UniqueName = "Windhammer"
	Thunderstroke                   UniqueName = "Thunderstroke"
	DemonsArch                      UniqueName = "Demon's Arch"
	Boneflame                       UniqueName = "Boneflame"
	Steelpillar                     UniqueName = "Steelpillar"
	NightwingsVeil                  UniqueName = "Nightwing's Veil"
	CrownofAges                     UniqueName = "Crown of Ages"
	AndarielsVisage                 UniqueName = "Andariel's Visage"
	Dragonscale                     UniqueName = "Dragonscale"
	SteelCarapice                   UniqueName = "Steel Carapice"
	MedusasGaze                     UniqueName = "Medusa's Gaze"
	Ravenlore                       UniqueName = "Ravenlore"
	Boneshade                       UniqueName = "Boneshade"
	Flamebellow                     UniqueName = "Flamebellow"
	Fathom                          UniqueName = "Fathom"
	Wolfhowl                        UniqueName = "Wolfhowl"
	SpiritWard                      UniqueName = "Spirit Ward"
	KirasGuardian                   UniqueName = "Kira's Guardian"
	OrmusRobes                      UniqueName = "Ormus' Robes"
	GheedsFortune                   UniqueName = "Gheed's Fortune"
	Stormlash                       UniqueName = "Stormlash"
	HalaberdsReign                  UniqueName = "Halaberd's Reign"
	SpikeThorn                      UniqueName = "Spike Thorn"
	DraculsGrasp                    UniqueName = "Dracul's Grasp"
	Frostwind                       UniqueName = "Frostwind"
	TemplarsMight                   UniqueName = "Templar's Might"
	Eschutastemper                  UniqueName = "Eschuta's temper"
	FirelizardsTalons               UniqueName = "Firelizard's Talons"
	SandstormTrek                   UniqueName = "Sandstorm Trek"
	Marrowwalk                      UniqueName = "Marrowwalk"
	HeavensLight                    UniqueName = "Heaven's Light"
	ArachnidMesh                    UniqueName = "Arachnid Mesh"
	NosferatusCoil                  UniqueName = "Nosferatu's Coil"
	Metalgrid                       UniqueName = "Metalgrid"
	VerdugosHeartyCord              UniqueName = "Verdugo's Hearty Cord"
	CarrionWind                     UniqueName = "Carrion Wind"
	Giantskull                      UniqueName = "Giantskull"
	Ironward                        UniqueName = "Ironward"
	Annihilus                       UniqueName = "Annihilus"
	AriocsNeedle                    UniqueName = "Arioc's Needle"
	Cranebeak                       UniqueName = "Cranebeak"
	NordsTenderizer                 UniqueName = "Nord's Tenderizer"
	Earthshifter                    UniqueName = "Earthshifter"
	Wraithflight                    UniqueName = "Wraithflight"
	Bonehew                         UniqueName = "Bonehew"
	OndalsWisdom                    UniqueName = "Ondal's Wisdom"
	TheReedeemer                    UniqueName = "The Reedeemer"
	HeadhuntersGlory                UniqueName = "Headhunter's Glory"
	Steelrend                       UniqueName = "Steelrend"
	RainbowFacetChainLightningDeath UniqueName = "Rainbow Facet (Chain Lightning Death)"
	RainbowFacetBlizzardDeath       UniqueName = "Rainbow Facet (Blizzard Death)"
	RainbowFacetMeteorDeath         UniqueName = "Rainbow Facet (Meteor Death)"
	RainbowFacetPoisonNovaDeath     UniqueName = "Rainbow Facet (Poison Nova Death)"
	RainbowFacetNovaLevel           UniqueName = "Rainbow Facet (Nova Level)"
	RainbowFacetFrostNovaLevel      UniqueName = "Rainbow Facet (Frost Nova Level)"
	RainbowFacetBlazeLevel          UniqueName = "Rainbow Facet (Blaze Level)"
	RainbowFacetVenomLevel          UniqueName = "Rainbow Facet (Venom Level)"
	HellfireTorch                   UniqueName = "Hellfire Torch"
	ColdRupture                     UniqueName = "Cold Rupture"
	FlameRift                       UniqueName = "Flame Rift"
	CrackoftheHeavens               UniqueName = "Crack of the Heavens"
	RottingFissure                  UniqueName = "Rotting Fissure"
	BoneBreak                       UniqueName = "Bone Break"
	BlackCleft                      UniqueName = "Black Cleft"
)

type UniqueItemInfo struct {
	Name     string
	Code     string
	LevelReq int
	Rarity   int
	ID       int
}

var UniqueItems = map[UniqueName]UniqueItemInfo{
	TheGnasher:                      {Name: "The Gnasher", Code: "hax", LevelReq: 5, Rarity: 1, ID: 0},
	Deathspade:                      {Name: "Deathspade", Code: "axe", LevelReq: 9, Rarity: 1, ID: 1},
	Bladebone:                       {Name: "Bladebone", Code: "2ax", LevelReq: 15, Rarity: 1, ID: 2},
	Mindrend:                        {Name: "Mindrend", Code: "mpi", LevelReq: 21, Rarity: 1, ID: 3},
	Rakescar:                        {Name: "Rakescar", Code: "wax", LevelReq: 27, Rarity: 1, ID: 4},
	FechmarsAxe:                     {Name: "Fechmars Axe", Code: "lax", LevelReq: 8, Rarity: 1, ID: 5},
	Goreshovel:                      {Name: "Goreshovel", Code: "bax", LevelReq: 14, Rarity: 1, ID: 6},
	TheChieftan:                     {Name: "The Chieftan", Code: "btx", LevelReq: 19, Rarity: 1, ID: 7},
	Brainhew:                        {Name: "Brainhew", Code: "gax", LevelReq: 25, Rarity: 1, ID: 8},
	TheHumongous:                    {Name: "The Humongous", Code: "gix", LevelReq: 29, Rarity: 1, ID: 9},
	IrosTorch:                       {Name: "Iros Torch", Code: "wnd", LevelReq: 5, Rarity: 1, ID: 10},
	Maelstromwrath:                  {Name: "Maelstromwrath", Code: "ywn", LevelReq: 14, Rarity: 1, ID: 11},
	Gravenspine:                     {Name: "Gravenspine", Code: "bwn", LevelReq: 20, Rarity: 1, ID: 12},
	UmesLament:                      {Name: "Umes Lament", Code: "gwn", LevelReq: 28, Rarity: 1, ID: 13},
	Felloak:                         {Name: "Felloak", Code: "clb", LevelReq: 3, Rarity: 1, ID: 14},
	KnellStriker:                    {Name: "Knell Striker", Code: "scp", LevelReq: 5, Rarity: 1, ID: 15},
	Rusthandle:                      {Name: "Rusthandle", Code: "gsc", LevelReq: 17, Rarity: 1, ID: 16},
	Stormeye:                        {Name: "Stormeye", Code: "wsp", LevelReq: 23, Rarity: 1, ID: 17},
	Stoutnail:                       {Name: "Stoutnail", Code: "spc", LevelReq: 5, Rarity: 1, ID: 18},
	Crushflange:                     {Name: "Crushflange", Code: "mac", LevelReq: 9, Rarity: 1, ID: 19},
	Bloodrise:                       {Name: "Bloodrise", Code: "mst", LevelReq: 15, Rarity: 1, ID: 20},
	TheGeneralsTanDoLiGa:            {Name: "The Generals Tan Do Li Ga", Code: "fla", LevelReq: 21, Rarity: 1, ID: 21},
	Ironstone:                       {Name: "Ironstone", Code: "whm", LevelReq: 27, Rarity: 1, ID: 22},
	Bonesob:                         {Name: "Bonesob", Code: "mau", LevelReq: 24, Rarity: 1, ID: 23},
	Steeldriver:                     {Name: "Steeldriver", Code: "gma", LevelReq: 29, Rarity: 1, ID: 24},
	RixotsKeen:                      {Name: "Rixots Keen", Code: "ssd", LevelReq: 2, Rarity: 1, ID: 25},
	BloodCrescent:                   {Name: "Blood Crescent", Code: "scm", LevelReq: 7, Rarity: 1, ID: 26},
	KrintizsSkewer:                  {Name: "Krintizs Skewer", Code: "sbr", LevelReq: 10, Rarity: 1, ID: 27},
	Gleamscythe:                     {Name: "Gleamscythe", Code: "flc", LevelReq: 13, Rarity: 1, ID: 28},
	GriswoldsEdge:                   {Name: "Griswolds Edge", Code: "bsd", LevelReq: 17, Rarity: 1, ID: 30},
	Hellplague:                      {Name: "Hellplague", Code: "lsd", LevelReq: 22, Rarity: 1, ID: 31},
	CulwensPoint:                    {Name: "Culwens Point", Code: "wsd", LevelReq: 29, Rarity: 1, ID: 32},
	Shadowfang:                      {Name: "Shadowfang", Code: "2hs", LevelReq: 12, Rarity: 1, ID: 33},
	Soulflay:                        {Name: "Soulflay", Code: "clm", LevelReq: 19, Rarity: 1, ID: 34},
	KinemilsAwl:                     {Name: "Kinemils Awl", Code: "gis", LevelReq: 23, Rarity: 1, ID: 35},
	Blacktongue:                     {Name: "Blacktongue", Code: "bsw", LevelReq: 26, Rarity: 1, ID: 36},
	Ripsaw:                          {Name: "Ripsaw", Code: "flb", LevelReq: 26, Rarity: 1, ID: 37},
	ThePatriarch:                    {Name: "The Patriarch", Code: "gsd", LevelReq: 29, Rarity: 1, ID: 38},
	Gull:                            {Name: "Gull", Code: "dgr", LevelReq: 4, Rarity: 1, ID: 39},
	TheDiggler:                      {Name: "The Diggler", Code: "dir", LevelReq: 11, Rarity: 1, ID: 40},
	TheJadeTanDo:                    {Name: "The Jade Tan Do", Code: "kri", LevelReq: 19, Rarity: 1, ID: 41},
	IricesShard:                     {Name: "Irices Shard", Code: "bld", LevelReq: 25, Rarity: 1, ID: 42},
	TheDragonChang:                  {Name: "The Dragon Chang", Code: "spr", LevelReq: 8, Rarity: 1, ID: 43},
	Razortine:                       {Name: "Razortine", Code: "tri", LevelReq: 12, Rarity: 1, ID: 44},
	Bloodthief:                      {Name: "Bloodthief", Code: "brn", LevelReq: 17, Rarity: 1, ID: 45},
	LanceofYaggai:                   {Name: "Lance of Yaggai", Code: "spt", LevelReq: 22, Rarity: 1, ID: 46},
	TheTannrGorerod:                 {Name: "The Tannr Gorerod", Code: "pik", LevelReq: 27, Rarity: 1, ID: 47},
	DimoaksHew:                      {Name: "Dimoaks Hew", Code: "bar", LevelReq: 8, Rarity: 1, ID: 48},
	Steelgoad:                       {Name: "Steelgoad", Code: "vou", LevelReq: 14, Rarity: 1, ID: 49},
	SoulHarvest:                     {Name: "Soul Harvest", Code: "scy", LevelReq: 19, Rarity: 1, ID: 50},
	TheBattlebranch:                 {Name: "The Battlebranch", Code: "pax", LevelReq: 25, Rarity: 1, ID: 51},
	Woestave:                        {Name: "Woestave", Code: "hal", LevelReq: 28, Rarity: 1, ID: 52},
	TheGrimReaper:                   {Name: "The Grim Reaper", Code: "wsc", LevelReq: 29, Rarity: 1, ID: 53},
	BaneAsh:                         {Name: "Bane Ash", Code: "sst", LevelReq: 5, Rarity: 1, ID: 54},
	SerpentLord:                     {Name: "Serpent Lord", Code: "lst", LevelReq: 9, Rarity: 1, ID: 55},
	LazarusSpire:                    {Name: "Lazarus Spire", Code: "cst", LevelReq: 18, Rarity: 1, ID: 56},
	TheSalamander:                   {Name: "The Salamander", Code: "bst", LevelReq: 21, Rarity: 1, ID: 57},
	TheIronJangBong:                 {Name: "The Iron Jang Bong", Code: "wst", LevelReq: 28, Rarity: 1, ID: 58},
	Pluckeye:                        {Name: "Pluckeye", Code: "sbw", LevelReq: 7, Rarity: 1, ID: 59},
	Witherstring:                    {Name: "Witherstring", Code: "hbw", LevelReq: 13, Rarity: 1, ID: 60},
	Rimeraven:                       {Name: "Rimeraven", Code: "lbw", LevelReq: 15, Rarity: 1, ID: 61},
	Piercerib:                       {Name: "Piercerib", Code: "cbw", LevelReq: 20, Rarity: 1, ID: 62},
	Pullspite:                       {Name: "Pullspite", Code: "sbb", LevelReq: 25, Rarity: 1, ID: 63},
	Wizendraw:                       {Name: "Wizendraw", Code: "lbb", LevelReq: 26, Rarity: 1, ID: 64},
	Hellclap:                        {Name: "Hellclap", Code: "swb", LevelReq: 27, Rarity: 1, ID: 65},
	Blastbark:                       {Name: "Blastbark", Code: "lwb", LevelReq: 28, Rarity: 1, ID: 66},
	Leadcrow:                        {Name: "Leadcrow", Code: "lxb", LevelReq: 9, Rarity: 1, ID: 67},
	Ichorsting:                      {Name: "Ichorsting", Code: "mxb", LevelReq: 18, Rarity: 1, ID: 68},
	Hellcast:                        {Name: "Hellcast", Code: "hxb", LevelReq: 27, Rarity: 1, ID: 69},
	Doomspittle:                     {Name: "Doomspittle", Code: "rxb", LevelReq: 28, Rarity: 1, ID: 70},
	WarBonnet:                       {Name: "War Bonnet", Code: "cap", LevelReq: 3, Rarity: 1, ID: 71},
	Tarnhelm:                        {Name: "Tarnhelm", Code: "skp", LevelReq: 15, Rarity: 1, ID: 72},
	CoifofGlory:                     {Name: "Coif of Glory", Code: "hlm", LevelReq: 14, Rarity: 1, ID: 73},
	Duskdeep:                        {Name: "Duskdeep", Code: "fhl", LevelReq: 17, Rarity: 1, ID: 74},
	Wormskull:                       {Name: "Wormskull", Code: "bhm", LevelReq: 21, Rarity: 1, ID: 75},
	Howltusk:                        {Name: "Howltusk", Code: "ghm", LevelReq: 25, Rarity: 1, ID: 76},
	UndeadCrown:                     {Name: "Undead Crown", Code: "crn", LevelReq: 29, Rarity: 1, ID: 77},
	TheFaceofHorror:                 {Name: "The Face of Horror", Code: "msk", LevelReq: 20, Rarity: 1, ID: 78},
	Greyform:                        {Name: "Greyform", Code: "qui", LevelReq: 7, Rarity: 1, ID: 79},
	BlinkbatsForm:                   {Name: "Blinkbats Form", Code: "lea", LevelReq: 12, Rarity: 1, ID: 80},
	TheCenturion:                    {Name: "The Centurion", Code: "hla", LevelReq: 14, Rarity: 1, ID: 81},
	Twitchthroe:                     {Name: "Twitchthroe", Code: "stu", LevelReq: 16, Rarity: 1, ID: 82},
	Darkglow:                        {Name: "Darkglow", Code: "rng", LevelReq: 14, Rarity: 1, ID: 83},
	Hawkmail:                        {Name: "Hawkmail", Code: "scl", LevelReq: 15, Rarity: 1, ID: 84},
	SparkingMail:                    {Name: "Sparking Mail", Code: "chn", LevelReq: 17, Rarity: 1, ID: 85},
	Venomsward:                      {Name: "Venomsward", Code: "brs", LevelReq: 20, Rarity: 1, ID: 86},
	Iceblink:                        {Name: "Iceblink", Code: "spl", LevelReq: 22, Rarity: 1, ID: 87},
	Boneflesh:                       {Name: "Boneflesh", Code: "plt", LevelReq: 26, Rarity: 1, ID: 88},
	Rockfleece:                      {Name: "Rockfleece", Code: "fld", LevelReq: 28, Rarity: 1, ID: 89},
	Rattlecage:                      {Name: "Rattlecage", Code: "gth", LevelReq: 29, Rarity: 1, ID: 90},
	Goldskin:                        {Name: "Goldskin", Code: "ful", LevelReq: 28, Rarity: 1, ID: 91},
	VictorsSilk:                     {Name: "Victors Silk", Code: "aar", LevelReq: 28, Rarity: 1, ID: 92},
	HeavenlyGarb:                    {Name: "Heavenly Garb", Code: "ltp", LevelReq: 29, Rarity: 1, ID: 93},
	PeltaLunata:                     {Name: "Pelta Lunata", Code: "buc", LevelReq: 2, Rarity: 1, ID: 94},
	UmbralDisk:                      {Name: "Umbral Disk", Code: "sml", LevelReq: 9, Rarity: 1, ID: 95},
	Stormguild:                      {Name: "Stormguild", Code: "lrg", LevelReq: 13, Rarity: 1, ID: 96},
	WalloftheEyeless:                {Name: "Wall of the Eyeless", Code: "bsh", LevelReq: 20, Rarity: 1, ID: 97},
	SwordbackHold:                   {Name: "Swordback Hold", Code: "spk", LevelReq: 15, Rarity: 1, ID: 98},
	Steelclash:                      {Name: "Steelclash", Code: "kit", LevelReq: 17, Rarity: 1, ID: 99},
	BverritKeep:                     {Name: "Bverrit Keep", Code: "tow", LevelReq: 19, Rarity: 1, ID: 100},
	TheWard:                         {Name: "The Ward", Code: "gts", LevelReq: 26, Rarity: 1, ID: 101},
	TheHandofBroc:                   {Name: "The Hand of Broc", Code: "lgl", LevelReq: 5, Rarity: 1, ID: 102},
	Bloodfist:                       {Name: "Bloodfist", Code: "vgl", LevelReq: 9, Rarity: 1, ID: 103},
	ChanceGuards:                    {Name: "Chance Guards", Code: "mgl", LevelReq: 15, Rarity: 1, ID: 104},
	Magefist:                        {Name: "Magefist", Code: "tgl", LevelReq: 23, Rarity: 1, ID: 105},
	Frostburn:                       {Name: "Frostburn", Code: "hgl", LevelReq: 29, Rarity: 1, ID: 106},
	Hotspur:                         {Name: "Hotspur", Code: "lbt", LevelReq: 5, Rarity: 1, ID: 107},
	Gorefoot:                        {Name: "Gorefoot", Code: "vbt", LevelReq: 9, Rarity: 1, ID: 108},
	TreadsofCthon:                   {Name: "Treads of Cthon", Code: "mbt", LevelReq: 15, Rarity: 1, ID: 109},
	GoblinToe:                       {Name: "Goblin Toe", Code: "tbt", LevelReq: 22, Rarity: 1, ID: 110},
	Tearhaunch:                      {Name: "Tearhaunch", Code: "hbt", LevelReq: 29, Rarity: 1, ID: 111},
	LenymsCord:                      {Name: "Lenyms Cord", Code: "lbl", LevelReq: 7, Rarity: 1, ID: 112},
	Snakecord:                       {Name: "Snakecord", Code: "vbl", LevelReq: 12, Rarity: 1, ID: 113},
	Nightsmoke:                      {Name: "Nightsmoke", Code: "mbl", LevelReq: 20, Rarity: 1, ID: 114},
	Goldwrap:                        {Name: "Goldwrap", Code: "tbl", LevelReq: 27, Rarity: 1, ID: 115},
	Bladebuckle:                     {Name: "Bladebuckle", Code: "hbl", LevelReq: 29, Rarity: 1, ID: 116},
	NokozanRelic:                    {Name: "Nokozan Relic", Code: "amu", LevelReq: 10, Rarity: 20, ID: 117},
	TheEyeofEtlich:                  {Name: "The Eye of Etlich", Code: "amu", LevelReq: 15, Rarity: 5, ID: 118},
	TheMahimOakCurio:                {Name: "The Mahim-Oak Curio", Code: "amu", LevelReq: 25, Rarity: 10, ID: 119},
	Nagelring:                       {Name: "Nagelring", Code: "rin", LevelReq: 7, Rarity: 15, ID: 120},
	ManaldHeal:                      {Name: "Manald Heal", Code: "rin", LevelReq: 15, Rarity: 15, ID: 121},
	TheStoneofJordan:                {Name: "The Stone of Jordan", Code: "rin", LevelReq: 29, Rarity: 1, ID: 122},
	AmuletoftheViper:                {Name: "Amulet of the Viper", Code: "vip", LevelReq: 0, Rarity: 1, ID: 123},
	StaffofKings:                    {Name: "Staff of Kings", Code: "msf", LevelReq: 0, Rarity: 1, ID: 124},
	HoradricStaff:                   {Name: "Horadric Staff", Code: "hst", LevelReq: 0, Rarity: 1, ID: 125},
	HellForgeHammer:                 {Name: "Hell Forge Hammer", Code: "hfh", LevelReq: 0, Rarity: 1, ID: 126},
	KhalimFlail:                     {Name: "KhalimFlail", Code: "qf1", LevelReq: 0, Rarity: 1, ID: 127},
	SuperKhalimFlail:                {Name: "SuperKhalimFlail", Code: "qf2", LevelReq: 0, Rarity: 1, ID: 128},
	Coldkill:                        {Name: "Coldkill", Code: "9ha", LevelReq: 36, Rarity: 1, ID: 129},
	ButchersPupil:                   {Name: "Butcher's Pupil", Code: "9ax", LevelReq: 39, Rarity: 1, ID: 130},
	Islestrike:                      {Name: "Islestrike", Code: "92a", LevelReq: 43, Rarity: 1, ID: 131},
	PompesWrath:                     {Name: "Pompe's Wrath", Code: "9mp", LevelReq: 45, Rarity: 1, ID: 132},
	GuardianNaga:                    {Name: "Guardian Naga", Code: "9wa", LevelReq: 48, Rarity: 1, ID: 133},
	WarlordsTrust:                   {Name: "Warlord's Trust", Code: "9la", LevelReq: 35, Rarity: 1, ID: 134},
	Spellsteel:                      {Name: "Spellsteel", Code: "9ba", LevelReq: 39, Rarity: 1, ID: 135},
	Stormrider:                      {Name: "Stormrider", Code: "9bt", LevelReq: 41, Rarity: 1, ID: 136},
	BoneslayerBlade:                 {Name: "Boneslayer Blade", Code: "9ga", LevelReq: 42, Rarity: 1, ID: 137},
	TheMinataur:                     {Name: "The Minataur", Code: "9gi", LevelReq: 45, Rarity: 1, ID: 138},
	SuicideBranch:                   {Name: "Suicide Branch", Code: "9wn", LevelReq: 33, Rarity: 1, ID: 139},
	CarinShard:                      {Name: "Carin Shard", Code: "9yw", LevelReq: 35, Rarity: 1, ID: 140},
	ArmofKingLeoric:                 {Name: "Arm of King Leoric", Code: "9bw", LevelReq: 36, Rarity: 1, ID: 141},
	BlackhandKey:                    {Name: "Blackhand Key", Code: "9gw", LevelReq: 41, Rarity: 1, ID: 142},
	DarkClanCrusher:                 {Name: "Dark Clan Crusher", Code: "9cl", LevelReq: 34, Rarity: 1, ID: 143},
	ZakarumsHand:                    {Name: "Zakarum's Hand", Code: "9sc", LevelReq: 37, Rarity: 1, ID: 144},
	TheFetidSprinkler:               {Name: "The Fetid Sprinkler", Code: "9qs", LevelReq: 38, Rarity: 1, ID: 145},
	HandofBlessedLight:              {Name: "Hand of Blessed Light", Code: "9ws", LevelReq: 42, Rarity: 1, ID: 146},
	Fleshrender:                     {Name: "Fleshrender", Code: "9sp", LevelReq: 38, Rarity: 1, ID: 147},
	SureshrillFrost:                 {Name: "Sureshrill Frost", Code: "9ma", LevelReq: 39, Rarity: 1, ID: 148},
	Moonfall:                        {Name: "Moonfall", Code: "9mt", LevelReq: 42, Rarity: 1, ID: 149},
	BaezilsVortex:                   {Name: "Baezil's Vortex", Code: "9fl", LevelReq: 45, Rarity: 1, ID: 150},
	Earthshaker:                     {Name: "Earthshaker", Code: "9wh", LevelReq: 43, Rarity: 1, ID: 151},
	BloodtreeStump:                  {Name: "Bloodtree Stump", Code: "9m9", LevelReq: 48, Rarity: 1, ID: 152},
	TheGavelofPain:                  {Name: "The Gavel of Pain", Code: "9gm", LevelReq: 45, Rarity: 1, ID: 153},
	Bloodletter:                     {Name: "Bloodletter", Code: "9ss", LevelReq: 30, Rarity: 1, ID: 154},
	ColdsteelEye:                    {Name: "Coldsteel Eye", Code: "9sm", LevelReq: 31, Rarity: 1, ID: 155},
	Hexfire:                         {Name: "Hexfire", Code: "9sb", LevelReq: 33, Rarity: 1, ID: 156},
	BladeofAliBaba:                  {Name: "Blade of Ali Baba", Code: "9fc", LevelReq: 35, Rarity: 1, ID: 157},
	GinthersRift:                    {Name: "Ginther's Rift", Code: "9cr", LevelReq: 37, Rarity: 1, ID: 158},
	Headstriker:                     {Name: "Headstriker", Code: "9bs", LevelReq: 39, Rarity: 1, ID: 159},
	PlagueBearer:                    {Name: "Plague Bearer", Code: "9ls", LevelReq: 41, Rarity: 1, ID: 160},
	TheAtlantian:                    {Name: "The Atlantian", Code: "9wd", LevelReq: 42, Rarity: 1, ID: 161},
	CrainteVomir:                    {Name: "Crainte Vomir", Code: "92h", LevelReq: 42, Rarity: 1, ID: 162},
	BingSzWang:                      {Name: "Bing Sz Wang", Code: "9cm", LevelReq: 43, Rarity: 1, ID: 163},
	TheVileHusk:                     {Name: "The Vile Husk", Code: "9gs", LevelReq: 44, Rarity: 1, ID: 164},
	Cloudcrack:                      {Name: "Cloudcrack", Code: "9b9", LevelReq: 45, Rarity: 1, ID: 165},
	TodesfaelleFlamme:               {Name: "Todesfaelle Flamme", Code: "9fb", LevelReq: 46, Rarity: 1, ID: 166},
	Swordguard:                      {Name: "Swordguard", Code: "9gd", LevelReq: 48, Rarity: 1, ID: 167},
	Spineripper:                     {Name: "Spineripper", Code: "9dg", LevelReq: 32, Rarity: 1, ID: 168},
	HeartCarver:                     {Name: "Heart Carver", Code: "9di", LevelReq: 36, Rarity: 1, ID: 169},
	BlackbogsSharp:                  {Name: "Blackbog's Sharp", Code: "9kr", LevelReq: 38, Rarity: 1, ID: 170},
	Stormspike:                      {Name: "Stormspike", Code: "9bl", LevelReq: 41, Rarity: 1, ID: 171},
	TheImpaler:                      {Name: "The Impaler", Code: "9sr", LevelReq: 31, Rarity: 1, ID: 172},
	KelpieSnare:                     {Name: "Kelpie Snare", Code: "9tr", LevelReq: 33, Rarity: 1, ID: 173},
	SoulfeastTine:                   {Name: "Soulfeast Tine", Code: "9br", LevelReq: 35, Rarity: 1, ID: 174},
	HoneSundan:                      {Name: "Hone Sundan", Code: "9st", LevelReq: 37, Rarity: 1, ID: 175},
	SpireofHonor:                    {Name: "Spire of Honor", Code: "9p9", LevelReq: 39, Rarity: 1, ID: 176},
	TheMeatScraper:                  {Name: "The Meat Scraper", Code: "9b7", LevelReq: 41, Rarity: 1, ID: 177},
	BlackleachBlade:                 {Name: "Blackleach Blade", Code: "9vo", LevelReq: 42, Rarity: 1, ID: 178},
	AthenasWrath:                    {Name: "Athena's Wrath", Code: "9s8", LevelReq: 42, Rarity: 1, ID: 179},
	PierreTombaleCouant:             {Name: "Pierre Tombale Couant", Code: "9pa", LevelReq: 43, Rarity: 1, ID: 180},
	HusoldalEvo:                     {Name: "Husoldal Evo", Code: "9h9", LevelReq: 44, Rarity: 1, ID: 181},
	GrimsBurningDead:                {Name: "Grim's Burning Dead", Code: "9wc", LevelReq: 45, Rarity: 1, ID: 182},
	Razorswitch:                     {Name: "Razorswitch", Code: "8ss", LevelReq: 28, Rarity: 1, ID: 183},
	Ribcracker:                      {Name: "Ribcracker", Code: "8ls", LevelReq: 31, Rarity: 1, ID: 184},
	ChromaticIre:                    {Name: "Chromatic Ire", Code: "8cs", LevelReq: 35, Rarity: 1, ID: 185},
	Warpspear:                       {Name: "Warpspear", Code: "8bs", LevelReq: 39, Rarity: 1, ID: 186},
	Skullcollector:                  {Name: "Skullcollector", Code: "8ws", LevelReq: 41, Rarity: 1, ID: 187},
	Skystrike:                       {Name: "Skystrike", Code: "8sb", LevelReq: 28, Rarity: 1, ID: 188},
	Riphook:                         {Name: "Riphook", Code: "8hb", LevelReq: 31, Rarity: 1, ID: 189},
	KukoShakaku:                     {Name: "Kuko Shakaku", Code: "8lb", LevelReq: 33, Rarity: 1, ID: 190},
	Endlesshail:                     {Name: "Endlesshail", Code: "8cb", LevelReq: 36, Rarity: 1, ID: 191},
	WhichwildString:                 {Name: "Whichwild String", Code: "8s8", LevelReq: 39, Rarity: 1, ID: 192},
	Cliffkiller:                     {Name: "Cliffkiller", Code: "8l8", LevelReq: 41, Rarity: 1, ID: 193},
	Magewrath:                       {Name: "Magewrath", Code: "8sw", LevelReq: 43, Rarity: 1, ID: 194},
	GodstrikeArch:                   {Name: "Godstrike Arch", Code: "8lw", LevelReq: 46, Rarity: 1, ID: 195},
	LangerBriser:                    {Name: "Langer Briser", Code: "8lx", LevelReq: 32, Rarity: 1, ID: 196},
	PusSpiter:                       {Name: "Pus Spiter", Code: "8mx", LevelReq: 36, Rarity: 1, ID: 197},
	BurizaDoKyanon:                  {Name: "Buriza-Do Kyanon", Code: "8hx", LevelReq: 41, Rarity: 1, ID: 198},
	DemonMachine:                    {Name: "Demon Machine", Code: "8rx", LevelReq: 49, Rarity: 1, ID: 199},
	PeasentCrown:                    {Name: "Peasent Crown", Code: "xap", LevelReq: 28, Rarity: 1, ID: 201},
	Rockstopper:                     {Name: "Rockstopper", Code: "xkp", LevelReq: 31, Rarity: 1, ID: 202},
	Stealskull:                      {Name: "Stealskull", Code: "xlm", LevelReq: 35, Rarity: 1, ID: 203},
	DarksightHelm:                   {Name: "Darksight Helm", Code: "xhl", LevelReq: 38, Rarity: 1, ID: 204},
	ValkiryWing:                     {Name: "Valkiry Wing", Code: "xhm", LevelReq: 44, Rarity: 1, ID: 205},
	CrownofThieves:                  {Name: "Crown of Thieves", Code: "xrn", LevelReq: 49, Rarity: 1, ID: 206},
	BlackhornsFace:                  {Name: "Blackhorn's Face", Code: "xsk", LevelReq: 41, Rarity: 1, ID: 207},
	Vampiregaze:                     {Name: "Vampiregaze", Code: "xh9", LevelReq: 41, Rarity: 1, ID: 208},
	TheSpiritShroud:                 {Name: "The Spirit Shroud", Code: "xui", LevelReq: 28, Rarity: 1, ID: 209},
	SkinoftheVipermagi:              {Name: "Skin of the Vipermagi", Code: "xea", LevelReq: 29, Rarity: 1, ID: 210},
	SkinoftheFlayerdOne:             {Name: "Skin of the Flayerd One", Code: "xla", LevelReq: 31, Rarity: 1, ID: 211},
	Ironpelt:                        {Name: "Ironpelt", Code: "xtu", LevelReq: 33, Rarity: 1, ID: 212},
	Spiritforge:                     {Name: "Spiritforge", Code: "xng", LevelReq: 35, Rarity: 1, ID: 213},
	CrowCaw:                         {Name: "Crow Caw", Code: "xcl", LevelReq: 37, Rarity: 1, ID: 214},
	Shaftstop:                       {Name: "Shaftstop", Code: "xhn", LevelReq: 38, Rarity: 1, ID: 215},
	DurielsShell:                    {Name: "Duriel's Shell", Code: "xrs", LevelReq: 41, Rarity: 1, ID: 216},
	SkulldersIre:                    {Name: "Skullder's Ire", Code: "xpl", LevelReq: 42, Rarity: 1, ID: 217},
	GuardianAngel:                   {Name: "Guardian Angel", Code: "xlt", LevelReq: 45, Rarity: 1, ID: 218},
	Toothrow:                        {Name: "Toothrow", Code: "xld", LevelReq: 48, Rarity: 1, ID: 219},
	AtmasWail:                       {Name: "Atma's Wail", Code: "xth", LevelReq: 51, Rarity: 1, ID: 220},
	BlackHades:                      {Name: "Black Hades", Code: "xul", LevelReq: 53, Rarity: 1, ID: 221},
	Corpsemourn:                     {Name: "Corpsemourn", Code: "xar", LevelReq: 55, Rarity: 1, ID: 222},
	QueHegansWisdon:                 {Name: "Que-Hegan's Wisdon", Code: "xtp", LevelReq: 51, Rarity: 1, ID: 223},
	Visceratuant:                    {Name: "Visceratuant", Code: "xuc", LevelReq: 28, Rarity: 1, ID: 224},
	MosersBlessedCircle:             {Name: "Mosers Blessed Circle", Code: "xml", LevelReq: 31, Rarity: 1, ID: 225},
	Stormchaser:                     {Name: "Stormchaser", Code: "xrg", LevelReq: 35, Rarity: 1, ID: 226},
	TiamatsRebuke:                   {Name: "Tiamat's Rebuke", Code: "xit", LevelReq: 38, Rarity: 1, ID: 227},
	KerkesSanctuary:                 {Name: "Kerke's Sanctuary", Code: "xow", LevelReq: 44, Rarity: 1, ID: 228},
	RadimantsSphere:                 {Name: "Radimant's Sphere", Code: "xts", LevelReq: 50, Rarity: 1, ID: 229},
	LidlessWall:                     {Name: "Lidless Wall", Code: "xsh", LevelReq: 41, Rarity: 1, ID: 230},
	LanceGuard:                      {Name: "Lance Guard", Code: "xpk", LevelReq: 35, Rarity: 1, ID: 231},
	VenomGrip:                       {Name: "Venom Grip", Code: "xlg", LevelReq: 29, Rarity: 1, ID: 232},
	Gravepalm:                       {Name: "Gravepalm", Code: "xvg", LevelReq: 32, Rarity: 1, ID: 233},
	Ghoulhide:                       {Name: "Ghoulhide", Code: "xmg", LevelReq: 36, Rarity: 1, ID: 234},
	Lavagout:                        {Name: "Lavagout", Code: "xtg", LevelReq: 42, Rarity: 1, ID: 235},
	Hellmouth:                       {Name: "Hellmouth", Code: "xhg", LevelReq: 47, Rarity: 1, ID: 236},
	Infernostride:                   {Name: "Infernostride", Code: "xlb", LevelReq: 29, Rarity: 1, ID: 237},
	Waterwalk:                       {Name: "Waterwalk", Code: "xvb", LevelReq: 32, Rarity: 1, ID: 238},
	Silkweave:                       {Name: "Silkweave", Code: "xmb", LevelReq: 36, Rarity: 1, ID: 239},
	Wartraveler:                     {Name: "Wartraveler", Code: "xtb", LevelReq: 42, Rarity: 1, ID: 240},
	Gorerider:                       {Name: "Gorerider", Code: "xhb", LevelReq: 47, Rarity: 1, ID: 241},
	StringofEars:                    {Name: "String of Ears", Code: "zlb", LevelReq: 29, Rarity: 1, ID: 242},
	Razortail:                       {Name: "Razortail", Code: "zvb", LevelReq: 32, Rarity: 1, ID: 243},
	Gloomstrap:                      {Name: "Gloomstrap", Code: "zmb", LevelReq: 36, Rarity: 1, ID: 244},
	Snowclash:                       {Name: "Snowclash", Code: "ztb", LevelReq: 42, Rarity: 1, ID: 245},
	ThudergodsVigor:                 {Name: "Thudergod's Vigor", Code: "zhb", LevelReq: 47, Rarity: 1, ID: 246},
	HarlequinCrest:                  {Name: "Harlequin Crest", Code: "uap", LevelReq: 62, Rarity: 1, ID: 248},
	VeilofSteel:                     {Name: "Veil of Steel", Code: "uhm", LevelReq: 73, Rarity: 1, ID: 249},
	TheGladiatorsBane:               {Name: "The Gladiator's Bane", Code: "utu", LevelReq: 85, Rarity: 1, ID: 250},
	ArkainesValor:                   {Name: "Arkaine's Valor", Code: "upl", LevelReq: 85, Rarity: 1, ID: 251},
	BlackoakShield:                  {Name: "Blackoak Shield", Code: "uml", LevelReq: 61, Rarity: 1, ID: 252},
	Stormshield:                     {Name: "Stormshield", Code: "uit", LevelReq: 73, Rarity: 1, ID: 253},
	Hellslayer:                      {Name: "Hellslayer", Code: "7bt", LevelReq: 66, Rarity: 1, ID: 254},
	MesserschmidtsReaver:            {Name: "Messerschmidt's Reaver", Code: "7ga", LevelReq: 70, Rarity: 1, ID: 255},
	BaranarsStar:                    {Name: "Baranar's Star", Code: "7mt", LevelReq: 65, Rarity: 1, ID: 256},
	SchaefersHammer:                 {Name: "Schaefer's Hammer", Code: "7wh", LevelReq: 79, Rarity: 1, ID: 257},
	TheCraniumBasher:                {Name: "The Cranium Basher", Code: "7gm", LevelReq: 87, Rarity: 1, ID: 258},
	Lightsabre:                      {Name: "Lightsabre", Code: "7cr", LevelReq: 58, Rarity: 5, ID: 259},
	Doombringer:                     {Name: "Doombringer", Code: "7b7", LevelReq: 69, Rarity: 1, ID: 260},
	TheGrandfather:                  {Name: "The Grandfather", Code: "7gd", LevelReq: 81, Rarity: 1, ID: 261},
	Wizardspike:                     {Name: "Wizardspike", Code: "7dg", LevelReq: 61, Rarity: 1, ID: 262},
	Stormspire:                      {Name: "Stormspire", Code: "7wc", LevelReq: 70, Rarity: 1, ID: 264},
	Eaglehorn:                       {Name: "Eaglehorn", Code: "6l7", LevelReq: 69, Rarity: 1, ID: 265},
	Windforce:                       {Name: "Windforce", Code: "6lw", LevelReq: 73, Rarity: 1, ID: 266},
	BulKathosWeddingBand:            {Name: "Bul Katho's Wedding Band", Code: "rin", LevelReq: 58, Rarity: 1, ID: 268},
	TheCatsEye:                      {Name: "The Cat's Eye", Code: "amu", LevelReq: 50, Rarity: 5, ID: 269},
	TheRisingSun:                    {Name: "The Rising Sun", Code: "amu", LevelReq: 65, Rarity: 5, ID: 270},
	CrescentMoon:                    {Name: "Crescent Moon", Code: "amu", LevelReq: 50, Rarity: 5, ID: 271},
	MarasKaleidoscope:               {Name: "Mara's Kaleidoscope", Code: "amu", LevelReq: 67, Rarity: 5, ID: 272},
	AtmasScarab:                     {Name: "Atma's Scarab", Code: "amu", LevelReq: 60, Rarity: 5, ID: 273},
	DwarfStar:                       {Name: "Dwarf Star", Code: "rin", LevelReq: 45, Rarity: 10, ID: 274},
	RavenFrost:                      {Name: "Raven Frost", Code: "rin", LevelReq: 45, Rarity: 10, ID: 275},
	HighlordsWrath:                  {Name: "Highlord's Wrath", Code: "amu", LevelReq: 65, Rarity: 5, ID: 276},
	SaracensChance:                  {Name: "Saracen's Chance", Code: "amu", LevelReq: 47, Rarity: 5, ID: 277},
	ArreatsFace:                     {Name: "Arreat's Face", Code: "baa", LevelReq: 42, Rarity: 1, ID: 279},
	Homunculus:                      {Name: "Homunculus", Code: "nea", LevelReq: 42, Rarity: 1, ID: 280},
	TitansRevenge:                   {Name: "Titan's Revenge", Code: "ama", LevelReq: 42, Rarity: 1, ID: 281},
	LycandersAim:                    {Name: "Lycander's Aim", Code: "am7", LevelReq: 42, Rarity: 1, ID: 282},
	LycandersFlank:                  {Name: "Lycander's Flank", Code: "am9", LevelReq: 42, Rarity: 1, ID: 283},
	TheOculus:                       {Name: "The Oculus", Code: "oba", LevelReq: 42, Rarity: 1, ID: 284},
	HeraldofZakarum:                 {Name: "Herald of Zakarum", Code: "pa9", LevelReq: 42, Rarity: 1, ID: 285},
	Cutthroat1:                      {Name: "Cutthroat1", Code: "9tw", LevelReq: 42, Rarity: 1, ID: 286},
	JalalsMane:                      {Name: "Jalal's Mane", Code: "dra", LevelReq: 42, Rarity: 1, ID: 287},
	TheScalper:                      {Name: "The Scalper", Code: "9ta", LevelReq: 57, Rarity: 1, ID: 288},
	Bloodmoon:                       {Name: "Bloodmoon", Code: "7sb", LevelReq: 61, Rarity: 1, ID: 289},
	Djinnslayer:                     {Name: "Djinnslayer", Code: "7sm", LevelReq: 65, Rarity: 1, ID: 290},
	Deathbit:                        {Name: "Deathbit", Code: "9tk", LevelReq: 44, Rarity: 1, ID: 291},
	Warshrike:                       {Name: "Warshrike", Code: "7bk", LevelReq: 75, Rarity: 1, ID: 292},
	Gutsiphon:                       {Name: "Gutsiphon", Code: "6rx", LevelReq: 71, Rarity: 1, ID: 293},
	Razoredge:                       {Name: "Razoredge", Code: "7ha", LevelReq: 67, Rarity: 1, ID: 294},
	Demonlimb:                       {Name: "Demonlimb", Code: "7sp", LevelReq: 63, Rarity: 1, ID: 296},
	Steelshade:                      {Name: "Steelshade", Code: "ulm", LevelReq: 62, Rarity: 1, ID: 297},
	TombReaver:                      {Name: "Tomb Reaver", Code: "7pa", LevelReq: 84, Rarity: 1, ID: 298},
	DeathssWeb:                      {Name: "Deaths's Web", Code: "7gw", LevelReq: 66, Rarity: 1, ID: 299},
	NaturesPeace:                    {Name: "Nature's Peace", Code: "rin", LevelReq: 69, Rarity: 3, ID: 300},
	Azurewrath:                      {Name: "Azurewrath", Code: "7cr", LevelReq: 85, Rarity: 1, ID: 301},
	SeraphsHymn:                     {Name: "Seraph's Hymn", Code: "amu", LevelReq: 65, Rarity: 3, ID: 302},
	Fleshripper:                     {Name: "Fleshripper", Code: "7kr", LevelReq: 68, Rarity: 1, ID: 304},
	HorizonsTornado:                 {Name: "Horizon's Tornado", Code: "7fl", LevelReq: 64, Rarity: 5, ID: 306},
	StoneCrusher:                    {Name: "Stone Crusher", Code: "7wh", LevelReq: 68, Rarity: 4, ID: 307},
	Jadetalon:                       {Name: "Jadetalon", Code: "7wb", LevelReq: 66, Rarity: 1, ID: 308},
	Shadowdancer:                    {Name: "Shadowdancer", Code: "uhb", LevelReq: 71, Rarity: 1, ID: 309},
	Cerebus:                         {Name: "Cerebus", Code: "drb", LevelReq: 63, Rarity: 1, ID: 310},
	TyraelsMight:                    {Name: "Tyrael's Might", Code: "uar", LevelReq: 84, Rarity: 1, ID: 311},
	Souldrain:                       {Name: "Souldrain", Code: "umg", LevelReq: 74, Rarity: 1, ID: 312},
	Runemaster:                      {Name: "Runemaster", Code: "72a", LevelReq: 72, Rarity: 1, ID: 313},
	Deathcleaver:                    {Name: "Deathcleaver", Code: "7wa", LevelReq: 70, Rarity: 1, ID: 314},
	ExecutionersJustice:             {Name: "Executioner's Justice", Code: "7gi", LevelReq: 75, Rarity: 1, ID: 315},
	Stoneraven:                      {Name: "Stoneraven", Code: "amd", LevelReq: 64, Rarity: 1, ID: 316},
	Leviathan:                       {Name: "Leviathan", Code: "uld", LevelReq: 65, Rarity: 1, ID: 317},
	Wisp:                            {Name: "Wisp", Code: "rin", LevelReq: 76, Rarity: 1, ID: 319},
	GargoylesBite:                   {Name: "Gargoyle's Bite", Code: "7ts", LevelReq: 70, Rarity: 1, ID: 320},
	Lacerator:                       {Name: "Lacerator", Code: "7b8", LevelReq: 68, Rarity: 1, ID: 321},
	MangSongsLesson:                 {Name: "Mang Song's Lesson", Code: "6ws", LevelReq: 82, Rarity: 1, ID: 322},
	Viperfork:                       {Name: "Viperfork", Code: "7br", LevelReq: 71, Rarity: 1, ID: 323},
	EtherealEdge:                    {Name: "Ethereal Edge", Code: "7ba", LevelReq: 74, Rarity: 1, ID: 324},
	DemonhornsEdge:                  {Name: "Demonhorn's Edge", Code: "bad", LevelReq: 61, Rarity: 1, ID: 325},
	TheReapersToll:                  {Name: "The Reaper's Toll", Code: "7s8", LevelReq: 75, Rarity: 1, ID: 326},
	Spiritkeeper:                    {Name: "Spiritkeeper", Code: "drd", LevelReq: 67, Rarity: 1, ID: 327},
	Hellrack:                        {Name: "Hellrack", Code: "6hx", LevelReq: 76, Rarity: 1, ID: 328},
	AlmaNegra:                       {Name: "Alma Negra", Code: "pac", LevelReq: 77, Rarity: 1, ID: 329},
	DarkforgeSpawn:                  {Name: "Darkforge Spawn", Code: "nef", LevelReq: 64, Rarity: 1, ID: 330},
	Widowmaker:                      {Name: "Widowmaker", Code: "6sw", LevelReq: 65, Rarity: 1, ID: 331},
	BloodravensCharge:               {Name: "Bloodraven's Charge", Code: "amb", LevelReq: 71, Rarity: 1, ID: 332},
	Ghostflame:                      {Name: "Ghostflame", Code: "7bl", LevelReq: 62, Rarity: 1, ID: 333},
	Shadowkiller:                    {Name: "Shadowkiller", Code: "7cs", LevelReq: 78, Rarity: 1, ID: 334},
	Gimmershred:                     {Name: "Gimmershred", Code: "7ta", LevelReq: 70, Rarity: 1, ID: 335},
	GriffonsEye:                     {Name: "Griffon's Eye", Code: "ci3", LevelReq: 76, Rarity: 1, ID: 336},
	Windhammer:                      {Name: "Windhammer", Code: "7m7", LevelReq: 68, Rarity: 1, ID: 337},
	Thunderstroke:                   {Name: "Thunderstroke", Code: "amf", LevelReq: 69, Rarity: 1, ID: 338},
	DemonsArch:                      {Name: "Demon's Arch", Code: "7s7", LevelReq: 68, Rarity: 1, ID: 340},
	Boneflame:                       {Name: "Boneflame", Code: "nee", LevelReq: 72, Rarity: 1, ID: 341},
	Steelpillar:                     {Name: "Steelpillar", Code: "7p7", LevelReq: 69, Rarity: 1, ID: 342},
	NightwingsVeil:                  {Name: "Nightwing's Veil", Code: "uhm", LevelReq: 67, Rarity: 1, ID: 343},
	CrownofAges:                     {Name: "Crown of Ages", Code: "urn", LevelReq: 82, Rarity: 1, ID: 344},
	AndarielsVisage:                 {Name: "Andariel's Visage", Code: "usk", LevelReq: 83, Rarity: 1, ID: 345},
	Dragonscale:                     {Name: "Dragonscale", Code: "pae", LevelReq: 80, Rarity: 1, ID: 347},
	SteelCarapice:                   {Name: "Steel Carapice", Code: "uul", LevelReq: 66, Rarity: 1, ID: 348},
	MedusasGaze:                     {Name: "Medusa's Gaze", Code: "uow", LevelReq: 76, Rarity: 1, ID: 349},
	Ravenlore:                       {Name: "Ravenlore", Code: "dre", LevelReq: 74, Rarity: 1, ID: 350},
	Boneshade:                       {Name: "Boneshade", Code: "7bw", LevelReq: 79, Rarity: 1, ID: 351},
	Flamebellow:                     {Name: "Flamebellow", Code: "7gs", LevelReq: 71, Rarity: 1, ID: 353},
	Fathom:                          {Name: "Fathom", Code: "obf", LevelReq: 73, Rarity: 1, ID: 354},
	Wolfhowl:                        {Name: "Wolfhowl", Code: "bac", LevelReq: 79, Rarity: 1, ID: 355},
	SpiritWard:                      {Name: "Spirit Ward", Code: "uts", LevelReq: 68, Rarity: 1, ID: 356},
	KirasGuardian:                   {Name: "Kira's Guardian", Code: "ci2", LevelReq: 77, Rarity: 1, ID: 357},
	OrmusRobes:                      {Name: "Ormus' Robes", Code: "uui", LevelReq: 75, Rarity: 1, ID: 358},
	GheedsFortune:                   {Name: "Gheed's Fortune", Code: "cm3", LevelReq: 62, Rarity: 1, ID: 359},
	Stormlash:                       {Name: "Stormlash", Code: "7fl", LevelReq: 82, Rarity: 1, ID: 360},
	HalaberdsReign:                  {Name: "Halaberd's Reign", Code: "bae", LevelReq: 77, Rarity: 1, ID: 361},
	SpikeThorn:                      {Name: "Spike Thorn", Code: "upk", LevelReq: 70, Rarity: 1, ID: 363},
	DraculsGrasp:                    {Name: "Dracul's Grasp", Code: "uvg", LevelReq: 76, Rarity: 1, ID: 364},
	Frostwind:                       {Name: "Frostwind", Code: "7ls", LevelReq: 70, Rarity: 1, ID: 365},
	TemplarsMight:                   {Name: "Templar's Might", Code: "uar", LevelReq: 74, Rarity: 8, ID: 366},
	Eschutastemper:                  {Name: "Eschuta's temper", Code: "obc", LevelReq: 72, Rarity: 1, ID: 367},
	FirelizardsTalons:               {Name: "Firelizard's Talons", Code: "7lw", LevelReq: 67, Rarity: 1, ID: 368},
	SandstormTrek:                   {Name: "Sandstorm Trek", Code: "uvb", LevelReq: 64, Rarity: 1, ID: 369},
	Marrowwalk:                      {Name: "Marrowwalk", Code: "umb", LevelReq: 66, Rarity: 1, ID: 370},
	HeavensLight:                    {Name: "Heaven's Light", Code: "7sc", LevelReq: 61, Rarity: 1, ID: 371},
	ArachnidMesh:                    {Name: "Arachnid Mesh", Code: "ulc", LevelReq: 80, Rarity: 1, ID: 373},
	NosferatusCoil:                  {Name: "Nosferatu's Coil", Code: "uvc", LevelReq: 51, Rarity: 1, ID: 374},
	Metalgrid:                       {Name: "Metalgrid", Code: "amu", LevelReq: 81, Rarity: 2, ID: 375},
	VerdugosHeartyCord:              {Name: "Verdugo's Hearty Cord", Code: "umc", LevelReq: 63, Rarity: 1, ID: 376},
	CarrionWind:                     {Name: "Carrion Wind", Code: "rin", LevelReq: 60, Rarity: 3, ID: 378},
	Giantskull:                      {Name: "Giantskull", Code: "uh9", LevelReq: 65, Rarity: 1, ID: 379},
	Ironward:                        {Name: "Ironward", Code: "7ws", LevelReq: 60, Rarity: 1, ID: 380},
	Annihilus:                       {Name: "Annihilus", Code: "cm1", LevelReq: 70, Rarity: 1, ID: 381},
	AriocsNeedle:                    {Name: "Arioc's Needle", Code: "7sr", LevelReq: 81, Rarity: 1, ID: 382},
	Cranebeak:                       {Name: "Cranebeak", Code: "7mp", LevelReq: 63, Rarity: 1, ID: 383},
	NordsTenderizer:                 {Name: "Nord's Tenderizer", Code: "7cl", LevelReq: 68, Rarity: 1, ID: 384},
	Earthshifter:                    {Name: "Earthshifter", Code: "7gm", LevelReq: 69, Rarity: 1, ID: 385},
	Wraithflight:                    {Name: "Wraithflight", Code: "7gl", LevelReq: 76, Rarity: 1, ID: 386},
	Bonehew:                         {Name: "Bonehew", Code: "7o7", LevelReq: 64, Rarity: 1, ID: 387},
	OndalsWisdom:                    {Name: "Ondal's Wisdom", Code: "6cs", LevelReq: 66, Rarity: 1, ID: 388},
	TheReedeemer:                    {Name: "The Reedeemer", Code: "7sc", LevelReq: 72, Rarity: 1, ID: 389},
	HeadhuntersGlory:                {Name: "Headhunter's Glory", Code: "ush", LevelReq: 75, Rarity: 1, ID: 390},
	Steelrend:                       {Name: "Steelrend", Code: "uhg", LevelReq: 70, Rarity: 1, ID: 391},
	RainbowFacetChainLightningDeath: {Name: "Rainbow Facet", Code: "jew", LevelReq: 49, Rarity: 1, ID: 392},
	RainbowFacetBlizzardDeath:       {Name: "Rainbow Facet", Code: "jew", LevelReq: 49, Rarity: 1, ID: 393},
	RainbowFacetMeteorDeath:         {Name: "Rainbow Facet", Code: "jew", LevelReq: 49, Rarity: 1, ID: 394},
	RainbowFacetPoisonNovaDeath:     {Name: "Rainbow Facet", Code: "jew", LevelReq: 49, Rarity: 1, ID: 395},
	RainbowFacetNovaLevel:           {Name: "Rainbow Facet", Code: "jew", LevelReq: 49, Rarity: 1, ID: 396},
	RainbowFacetFrostNovaLevel:      {Name: "Rainbow Facet", Code: "jew", LevelReq: 49, Rarity: 1, ID: 397},
	RainbowFacetBlazeLevel:          {Name: "Rainbow Facet", Code: "jew", LevelReq: 49, Rarity: 1, ID: 398},
	RainbowFacetVenomLevel:          {Name: "Rainbow Facet", Code: "jew", LevelReq: 49, Rarity: 1, ID: 399},
	HellfireTorch:                   {Name: "Hellfire Torch", Code: "cm2", LevelReq: 75, Rarity: 1, ID: 400},
	ColdRupture:                     {Name: "Cold Rupture", Code: "cm3", LevelReq: 75, Rarity: 1, ID: 401},
	FlameRift:                       {Name: "Flame Rift", Code: "cm3", LevelReq: 75, Rarity: 1, ID: 402},
	CrackoftheHeavens:               {Name: "Crack of the Heavens", Code: "cm3", LevelReq: 75, Rarity: 1, ID: 403},
	RottingFissure:                  {Name: "Rotting Fissure", Code: "cm3", LevelReq: 75, Rarity: 1, ID: 404},
	BoneBreak:                       {Name: "Bone Break", Code: "cm3", LevelReq: 75, Rarity: 1, ID: 405},
	BlackCleft:                      {Name: "Black Cleft", Code: "cm3", LevelReq: 75, Rarity: 1, ID: 406},
}
